#!/usr/bin/env bun
/**
 * ACT-CLINEMM-FORK-BASELINE01-CORRECTION11 — Closure logic (pure).
 *
 * The renderer (`render-baseline-report.ts`) imports the helpers from this
 * module so the verdict logic is independently testable. Importing this
 * module has no side effects — it does not read the working tree, write any
 * file, or spawn git. The renderer's main entry performs I/O and calls into
 * `computeClosure` / `checkEvidence`.
 *
 * Policy (CORRECTION11, fail-closed + non-self-referential subject-tree +
 * separated execution identity + per-command drift attestation):
 *
 *   FAIL      evidence is missing, malformed, stale-bound, hash-invalid,
 *             multi-tree, command-set-mismatched, symlinked,
 *             outside-evidence-dir, self-referential, on-a-dirty-worktree,
 *             split between subject and execution identity, captured
 *             with drift between/within commands, or recorded with
 *             malformed paths; OR there are UNKNOWN-classified failures
 *             with no investigation note.
 *   PARTIAL   evidence is internally valid and command-set-exact (incl. per-
 *             record equality), the UNKNOWN policy is satisfied, but at
 *             least one declared baseline requirement (R4/R5/R6/R7/R16)
 *             remains open.
 *   PASS      every requirement is satisfied and all mandatory commands
 *             pass on the binding host.
 *
 * CORRECTION11 binding model — runner drift attestation:
 *
 *   Tracked files generated by the verification workflow are still
 *   structurally excluded from the subject tree (CORRECTION10). The
 *   runner now records four additional attestations:
 *
 *     subject_tree_oid_before / subject_tree_oid_after
 *                          — filtered OID captured before and after
 *                            the matrix. Required to be equal.
 *     executionIdentityValid
 *                          — `git cat-file -e <head>^{commit}` and
 *                            `git cat-file -e <tree>^{tree}` both
 *                            succeed, AND
 *                            `git rev-parse <head>^{tree}` equals
 *                            `execution_tree_oid`.
 *     worktreeInputsCleanBefore / worktreeInputsCleanAfter
 *                          — `boolean | null` tri-state; the runner
 *                            captures path-aware cleanliness (every
 *                            path except declared expected outputs)
 *                            before and after the matrix. Required to
 *                            be `true` for verdict to leave FAIL on
 *                            these grounds. `null` means "not recorded".
 *     perCommandDriftChecked
 *                          — every command row has equal before/after
 *                            HEAD/tree/subject fields, captured by the
 *                            runner immediately around the command.
 *
 *   These fields were added because the CORRECTION10 reviewer found
 *   that the runner:
 *
 *     1. Sampled cleanliness only after the matrix (R1).
 *     2. Could not satisfy post-run cleanliness with tracked outputs
 *        on the same worktree (R2).
 *     3. Only syntax-checked the execution OIDs, not that they form a
 *        valid Git object pair (R3).
 *     4. Stamped every command row with the same `execTree` captured
 *        before the matrix, so HEAD/tree drift mid-run was silent (R4).
 *     5. Captured the subject only after execution, not before (R5).
 *     6. Recorded stdout/stderr paths as repo-relative rather than
 *        evidence-dir-relative, leaving the manifest path model
 *        inconsistent (R6).
 *
 *   CORRECTION11 closes each of these by failing closed on the new
 *   reason codes:
 *     EXECUTION_IDENTITY_INVALID
 *     WORKTREE_INPUTS_DIRTY_BEFORE
 *     WORKTREE_INPUTS_DIRTY_AFTER
 *     SUBJECT_DRIFT
 *     REPOSITORY_DRIFT
 *     MANIFEST_PATH_OUTSIDE_EVIDENCE
 *
 * Every evidence dimension must hold simultaneously for the verdict to
 * not be FAIL on evidence grounds:
 *
 *   - evidence.json exists and was JSON-decodable
 *   - subject binding matches (subject_tree_oid comparison)
 *   - execution identity is well-formed and its head/tree are related
 *     (`head^{tree} == tree`); the bundle's execution_tree_oid equals
 *     every command's tree_oid, and there is exactly one tree
 *   - subject and execution identity remained stable across the matrix
 *     (no per-command drift; before/after captured and equal)
 *   - subject inputs were clean before and after the matrix
 *   - hash manifest is well-formed, contained under the evidence
 *     directory, duplicate-free, contains no absolute/traversal paths,
 *     and every declared payload path exists, matches its declared
 *     SHA-256, and is not a symlink
 *   - on-disk non-control files in the evidence directory are all
 *     declared in the manifest (hashes.sha256 itself is a control file
 *     and exempt)
 *   - every executed command has exactly one matching evidence row, no
 *     duplicates in either set, no malformed rows, and per-ID field
 *     equality (status, head/tree, exit_code, timeout, hashes,
 *     classification)
 *
 * Note: `evidence.head_oid` is *informational*. Its well-formedness is
 * documented for traceability but does NOT drive closure — only the
 * subject tree and execution identity do.
 */

import { existsSync, readFileSync, readdirSync, lstatSync } from "node:fs";
import { createHash } from "node:crypto";
import {
	isAbsolute,
	join,
	relative,
	resolve,
	sep,
} from "node:path";

export type Verdict = "PASS" | "PARTIAL" | "FAIL";

export type ReasonCode =
	| "EVIDENCE_INCOMPLETE"
	| "SUBJECT_TREE_COMPUTATION_FAILED"
	| "SUBJECT_TREE_CONTRACT_MISSING"
	| "EXECUTION_IDENTITY_MISSING"
	| "EXECUTION_IDENTITY_MALFORMED"
	| "EXECUTION_IDENTITY_INVALID"
	| "EXECUTION_TREE_NOT_BOUND"
	| "EXECUTION_TREES_MIXED"
	| "WORKTREE_INPUTS_DIRTY_BEFORE"
	| "WORKTREE_INPUTS_DIRTY_AFTER"
	| "SUBJECT_DRIFT"
	| "REPOSITORY_DRIFT"
	| "MANIFEST_PATH_OUTSIDE_EVIDENCE"
	| "UNKNOWN_FAILURES_PRESENT"
	| "R4_UNSATISFIED"
	| "R5_UNSATISFIED"
	| "R6_UNSATISFIED"
	| "R7_UNSATISFIED"
	| "R16_UNSATISFIED"
	| "MANDATORY_NOT_ALL_PASS"
	| "AFFECTED_SCOPE_NOT_ALL_PASS";

export interface PathDiagnostic {
	path: string;
	reason: "missing" | "unexpected" | "symlink" | "traversal" | "absolute" | "outside-evidence-dir";
}

export interface HashMismatch {
	path: string;
	expected: string;
	actual: string;
}

export interface MalformedLine {
	line: number;
	content: string;
}

export interface DuplicatePath {
	path: string;
	occurrences: number;
}

export interface CommandRecordMismatch {
	id: string;
	fields: string[];
	evidence: Record<string, unknown>;
	executed: Record<string, unknown>;
}

/**
 * The complete integrity picture for the detached evidence bundle. Every
 * dimension must be satisfied for the verdict to not be FAIL on evidence
 * grounds; see `isEvidenceOk` and `computeClosure`.
 */
export interface EvidenceView {
	/** The evidence.json file existed and was JSON-decodable. */
	exists: boolean;
	/** Information-only: evidence.head_oid is a syntactically valid 40-char lowercase hex OID. Not in the closure conjunction. */
	headOidWellformed: boolean;
	/** Subject binding holds: `subject_tree_oid` matches the renderer's freshly-computed filtered tree. */
	treeMatches: boolean;
	/** Whether the bundle used the new subject-tree contract (true) or fell back to legacy literal `tree_oid`/`HEAD^{tree}` (false). */
	subjectTreeContract: boolean;
	/** Whether the renderer could compute the current filtered subject-tree OID. False ⇒ closure must fail (SUBJECT_TREE_COMPUTATION_FAILED). */
	subjectTreeComputationOk: boolean;
	/** Whether the bundle carries the new execution-identity fields (CORRECTION10/11). False ⇒ closure must fail (EXECUTION_IDENTITY_MISSING). */
	executionIdentityRecorded: boolean;
	/** Whether `evidence.execution_head_oid` is a syntactically valid OID. */
	executionHeadOidWellformed: boolean;
	/** Whether `evidence.execution_tree_oid` is a syntactically valid OID. */
	executionTreeOidWellformed: boolean;
	/**
	 * CORRECTION11: `git cat-file -e <head>^{commit}` and
	 * `git cat-file -e <tree>^{tree}` succeed AND
	 * `git rev-parse <head>^{tree}` equals `execution_tree_oid`.
	 */
	executionIdentityValid: boolean;
	/** All command rows have a single execution-tree value, matching `evidence.execution_tree_oid`. */
	executionTreeBound: boolean;
	/** The set of distinct execution-tree values across command rows. Length must be exactly 1. */
	executionTrees: string[];
	/**
	 * CORRECTION11 tri-state cleanliness: `true` if recorded-and-clean,
	 * `false` if recorded-and-dirty, `null` if the field is absent.
	 */
	worktreeInputsCleanBefore: boolean | null;
	worktreeInputsCleanAfter: boolean | null;
	/**
	 * CORRECTION11: every command row records equal
	 * `head_oid_before`/`head_oid_after`, `tree_oid_before`/`tree_oid_after`,
	 * and `subject_tree_oid_before`/`subject_tree_oid_after`, each
	 * pinning the bundle's execution identity. This field collapses the
	 * per-command check into a single boolean on the bundle.
	 */
	perCommandDriftChecked: boolean;
	/**
	 * CORRECTION11: the bundle records both `subject_tree_oid_before`
	 * and `subject_tree_oid_after`, both equal to the recorded
	 * `subject_tree_oid`. Indicates the subject identity was stable
	 * across the matrix.
	 */
	subjectStableAcrossMatrix: boolean;
	/**
	 * CORRECTION11: the bundle records `expected_output_paths` and the
	 * manifest declares every declared path. Indicates the runner's
	 * evidence-directory-relative path contract is honored.
	 */
	manifestContractHonored: boolean;
	/** Manifest is well-formed and every declared path matches its declared hash. */
	hashManifestValid: boolean;
	missingFiles: PathDiagnostic[];
	unexpectedFiles: PathDiagnostic[];
	hashMismatches: HashMismatch[];
	malformedLines: MalformedLine[];
	duplicatePaths: DuplicatePath[];
	commandSetExact: boolean;
	duplicateEvidenceCommandIds: DuplicatePath[];
	duplicateExecutedCommandIds: DuplicatePath[];
	commandRecordMismatches: CommandRecordMismatch[];
	rejectedManifestPaths: PathDiagnostic[];
	outOfEvidenceDirPaths: PathDiagnostic[];
	malformedEvidenceCommandRows: number;
	malformedExecutedCommandRows: number;
	decodeError: string | null;
}

export interface ClosureInput {
	evidence: EvidenceView;
	unknownFailures: string[];
	unknownFailureCount: number;
	mandatoryPass: number;
	mandatoryFail: number;
	mandatoryApplicable: number;
	affectedScopePass: number;
	affectedScopeFail: number;
	affectedScopeApplicable: number;
	r4Satisfied: boolean;
	r5Satisfied: boolean;
	r6Satisfied: boolean;
	r7Satisfied: boolean;
	r16Satisfied: boolean;
}

export interface ClosureResult {
	verdict: Verdict;
	evidenceOk: boolean;
	reasonCodes: ReasonCode[];
	unknownFailureCount: number;
}

// ---------- control files ---------------------------------------------------

export const CONTROL_FILES: ReadonlySet<string> = new Set(["hashes.sha256"]);

const RECORD_COMPARE_FIELDS = [
	"status",
	"head_oid",
	"tree_oid",
	"exit_code",
	"timeout",
	"stdout_sha256",
	"stderr_sha256",
	"environment_sha256",
	"failure_classification",
] as const;

const OID_PATTERN = /^[0-9a-f]{40}$/;

// ---------- closure decision ------------------------------------------------

export function computeClosure(input: ClosureInput): ClosureResult {
	const r4 = input.r4Satisfied;
	const r5 = input.r5Satisfied;
	const r6 = input.r6Satisfied;
	const r7 = input.r7Satisfied;
	const r16 = input.r16Satisfied;

	const unknownCount =
		input.unknownFailures.length + Math.max(0, input.unknownFailureCount);
	const hasUnknown = unknownCount > 0;

	const allMandatoryPass =
		input.mandatoryApplicable > 0 && input.mandatoryPass === input.mandatoryApplicable;
	const allAffectedPass =
		input.affectedScopeApplicable === 0 ||
		input.affectedScopePass === input.affectedScopeApplicable;

	const evidenceOk = isEvidenceOk(input.evidence);

	const reasonCodes: ReasonCode[] = [];
	if (!evidenceOk) reasonCodes.push("EVIDENCE_INCOMPLETE");
	if (!input.evidence.subjectTreeComputationOk) reasonCodes.push("SUBJECT_TREE_COMPUTATION_FAILED");
	if (!input.evidence.subjectTreeContract) reasonCodes.push("SUBJECT_TREE_CONTRACT_MISSING");
	if (!input.evidence.executionIdentityRecorded) reasonCodes.push("EXECUTION_IDENTITY_MISSING");
	if (!input.evidence.executionHeadOidWellformed || !input.evidence.executionTreeOidWellformed) {
		reasonCodes.push("EXECUTION_IDENTITY_MALFORMED");
	}
	if (input.evidence.executionIdentityRecorded && !input.evidence.executionIdentityValid) {
		reasonCodes.push("EXECUTION_IDENTITY_INVALID");
	}
	if (input.evidence.executionTrees.length > 1) {
		reasonCodes.push("EXECUTION_TREES_MIXED");
	}
	if (
		input.evidence.executionTrees.length === 1 &&
		!input.evidence.executionTreeBound
	) {
		reasonCodes.push("EXECUTION_TREE_NOT_BOUND");
	}
	if (input.evidence.worktreeInputsCleanBefore === false) {
		reasonCodes.push("WORKTREE_INPUTS_DIRTY_BEFORE");
	}
	if (input.evidence.worktreeInputsCleanAfter === false) {
		reasonCodes.push("WORKTREE_INPUTS_DIRTY_AFTER");
	}
	if (
		input.evidence.executionIdentityRecorded &&
		!input.evidence.subjectStableAcrossMatrix
	) {
		reasonCodes.push("SUBJECT_DRIFT");
	}
	if (
		input.evidence.executionIdentityRecorded &&
		!input.evidence.perCommandDriftChecked
	) {
		reasonCodes.push("REPOSITORY_DRIFT");
	}
	if (!input.evidence.manifestContractHonored) {
		reasonCodes.push("MANIFEST_PATH_OUTSIDE_EVIDENCE");
	}
	if (hasUnknown) reasonCodes.push("UNKNOWN_FAILURES_PRESENT");
	if (!r4) reasonCodes.push("R4_UNSATISFIED");
	if (!r5) reasonCodes.push("R5_UNSATISFIED");
	if (!r6) reasonCodes.push("R6_UNSATISFIED");
	if (!r7) reasonCodes.push("R7_UNSATISFIED");
	if (!r16) reasonCodes.push("R16_UNSATISFIED");
	if (!allMandatoryPass) reasonCodes.push("MANDATORY_NOT_ALL_PASS");
	if (!allAffectedPass) reasonCodes.push("AFFECTED_SCOPE_NOT_ALL_PASS");

	let verdict: Verdict;
	if (!evidenceOk) {
		verdict = "FAIL";
	} else if (hasUnknown) {
		verdict = "FAIL";
	} else if (r4 && r5 && r6 && r7 && r16 && allMandatoryPass && allAffectedPass) {
		verdict = "PASS";
	} else {
		verdict = "PARTIAL";
	}

	return {
		verdict,
		evidenceOk,
		reasonCodes,
		unknownFailureCount: unknownCount,
	};
}

/**
 * True iff every dimension of the evidence view is satisfied. This is the
 * single source of truth used by both `computeClosure` and the tests; do
 * not re-derive `evidenceOk` ad-hoc elsewhere.
 */
export function isEvidenceOk(e: EvidenceView): boolean {
	return (
		e.exists &&
		e.subjectTreeComputationOk && // CORRECTION09: filtered tree must compute
		e.subjectTreeContract && // CORRECTION09/10: must be on the new contract
		e.executionIdentityRecorded && // CORRECTION10/11: subject/execution split recorded
		e.executionHeadOidWellformed && // CORRECTION10
		e.executionTreeOidWellformed && // CORRECTION10
		e.executionIdentityValid && // CORRECTION11: head^{tree} == tree
		e.worktreeInputsCleanBefore === true && // CORRECTION11: clean before
		e.worktreeInputsCleanAfter === true && // CORRECTION11: clean after
		e.subjectStableAcrossMatrix && // CORRECTION11: subject unchanged across matrix
		e.perCommandDriftChecked && // CORRECTION11: every command had equal before/after
		e.manifestContractHonored && // CORRECTION11: every declared path is in the evidence dir
		e.treeMatches &&
		e.executionTreeBound &&
		e.executionTrees.length === 1 &&
		e.hashManifestValid &&
		e.missingFiles.length === 0 &&
		e.unexpectedFiles.length === 0 &&
		e.hashMismatches.length === 0 &&
		e.malformedLines.length === 0 &&
		e.duplicatePaths.length === 0 &&
		e.commandSetExact &&
		e.duplicateEvidenceCommandIds.length === 0 &&
		e.duplicateExecutedCommandIds.length === 0 &&
		e.commandRecordMismatches.length === 0 &&
		e.rejectedManifestPaths.length === 0 &&
		e.outOfEvidenceDirPaths.length === 0 &&
		e.malformedEvidenceCommandRows === 0 &&
		e.malformedExecutedCommandRows === 0 &&
		e.decodeError === null
	);
}

// ---------- structured evidence check ---------------------------------------

interface CheckEvidenceArgs {
	ev: { ok: boolean; value: unknown; error: string | null };
	hashesText: string;
	evDirAbs: string;
	executedCmds: any[];
	rootAbs: string;
	headOidNow: string;
	treeOidNow: string;
	/**
	 * The current filtered subject-tree OID (HEAD^{tree} minus
	 * `SUBJECT_TREE_EXCLUDES`). If supplied, the binding subject is
	 * `evidence.subject_tree_oid` and this must match. `null` here means
	 * the renderer could not compute the filtered tree, in which case
	 * `subjectTreeComputationOk` becomes `false`.
	 */
	filteredSubjectTreeOidNow?: string | null;
	/**
	 * CORRECTION11: result of `git rev-parse <execution_head_oid>^{tree}`
	 * and `git cat-file -e` checks. `null` means the renderer did not
	 * perform this check (legacy bundle).
	 */
	executionIdentityValidNow?: boolean | null;
}

export function checkEvidence(args: CheckEvidenceArgs): EvidenceView {
	const {
		ev,
		hashesText,
		evDirAbs,
		executedCmds,
		rootAbs,
		headOidNow: _headOidNow,
		treeOidNow,
		filteredSubjectTreeOidNow = null,
		executionIdentityValidNow = null,
	} = args;

	const out: EvidenceView = {
		exists: ev.ok,
		headOidWellformed: false,
		treeMatches: false,
		subjectTreeContract: false,
		subjectTreeComputationOk: filteredSubjectTreeOidNow !== null,
		executionIdentityRecorded: false,
		executionHeadOidWellformed: false,
		executionTreeOidWellformed: false,
		executionIdentityValid: false,
		executionTreeBound: false,
		executionTrees: [],
		worktreeInputsCleanBefore: null,
		worktreeInputsCleanAfter: null,
		perCommandDriftChecked: false,
		subjectStableAcrossMatrix: false,
		manifestContractHonored: false,
		hashManifestValid: false,
		missingFiles: [],
		unexpectedFiles: [],
		hashMismatches: [],
		malformedLines: [],
		duplicatePaths: [],
		commandSetExact: false,
		duplicateEvidenceCommandIds: [],
		duplicateExecutedCommandIds: [],
		commandRecordMismatches: [],
		rejectedManifestPaths: [],
		outOfEvidenceDirPaths: [],
		malformedEvidenceCommandRows: 0,
		malformedExecutedCommandRows: 0,
		decodeError: ev.error,
	};

	const evObj = ev.ok && typeof ev.value === "object" && ev.value !== null ? (ev.value as any) : null;
	if (!evObj) return out;

	out.headOidWellformed =
		typeof evObj.head_oid === "string" && OID_PATTERN.test(evObj.head_oid);

	// Subject binding (CORRECTION08/10/11): the contract requires a
	// `subject_tree_oid` field on the evidence object, equal to the
	// renderer's freshly-computed filtered tree.
	const subjectTreeFromEvidence =
		typeof evObj.subject_tree_oid === "string" ? evObj.subject_tree_oid : null;
	const filteredTree =
		typeof filteredSubjectTreeOidNow === "string" && filteredSubjectTreeOidNow.length > 0
			? filteredSubjectTreeOidNow
			: null;
	if (subjectTreeFromEvidence && filteredTree) {
		out.subjectTreeContract = true;
		out.treeMatches = subjectTreeFromEvidence === filteredTree;
	} else {
		out.subjectTreeContract = false;
		out.treeMatches = false;
	}

	// Execution identity (CORRECTION10/11): the bundle records
	// execution_head_oid, execution_tree_oid, and the worktree clean
	// state at start and end of the matrix.
	const executionHeadFromEvidence =
		typeof evObj.execution_head_oid === "string" ? evObj.execution_head_oid : null;
	const executionTreeFromEvidence =
		typeof evObj.execution_tree_oid === "string" ? evObj.execution_tree_oid : null;
	const worktreeInputsCleanBefore =
		typeof evObj.worktree_inputs_clean_before === "boolean"
			? evObj.worktree_inputs_clean_before
			: typeof evObj.worktree_clean_before === "boolean" // CORRECTION10 legacy field
				? evObj.worktree_clean_before
				: undefined;
	const worktreeInputsCleanAfter =
		typeof evObj.worktree_inputs_clean_after === "boolean"
			? evObj.worktree_inputs_clean_after
			: typeof evObj.worktree_clean_after === "boolean" // CORRECTION10 legacy field
				? evObj.worktree_clean_after
				: undefined;

	out.executionIdentityRecorded =
		executionHeadFromEvidence !== null &&
		executionTreeFromEvidence !== null &&
		worktreeInputsCleanBefore !== undefined &&
		worktreeInputsCleanAfter !== undefined;
	// Bundle-derived execution identity attestation: the runner
	// records `execution_identity_valid` after running `git cat-file -e`
	// and `git rev-parse <head>^{tree} == <tree>`. This is the
	// authoritative value when the renderer does not perform its
	// own check (default behavior in CORRECTION11).
	const bundleExecutionIdentityValid =
		typeof evObj.execution_identity_valid === "boolean"
			? evObj.execution_identity_valid
			: undefined;
	if (bundleExecutionIdentityValid !== undefined) {
		out.executionIdentityValid = bundleExecutionIdentityValid;
	}
	out.executionHeadOidWellformed =
		executionHeadFromEvidence !== null && OID_PATTERN.test(executionHeadFromEvidence);
	out.executionTreeOidWellformed =
		executionTreeFromEvidence !== null && OID_PATTERN.test(executionTreeFromEvidence);
	out.worktreeInputsCleanBefore = worktreeInputsCleanBefore ?? null;
	out.worktreeInputsCleanAfter = worktreeInputsCleanAfter ?? null;

	// CORRECTION11: subject tree was captured before AND after the matrix,
	// and both equal the recorded `subject_tree_oid`.
	const subjectTreeBefore =
		typeof evObj.subject_tree_oid_before === "string" ? evObj.subject_tree_oid_before : null;
	const subjectTreeAfter =
		typeof evObj.subject_tree_oid_after === "string" ? evObj.subject_tree_oid_after : null;
	out.subjectStableAcrossMatrix =
		subjectTreeBefore !== null &&
		subjectTreeAfter !== null &&
		subjectTreeFromEvidence !== null &&
		subjectTreeBefore === subjectTreeAfter &&
		subjectTreeBefore === subjectTreeFromEvidence;

	// CORRECTION11: manifest path contract. The runner declares
	// `expected_output_paths` and the manifest must declare every
	// declared path inside the evidence directory.
	const expectedOutputPaths = Array.isArray(evObj.expected_output_paths)
		? (evObj.expected_output_paths as unknown[]).filter((p) => typeof p === "string")
		: null;
	if (expectedOutputPaths === null) {
		out.manifestContractHonored = false;
	} else {
		// Will be re-evaluated after manifest parsing below using the
		// set of declared paths.
		out.manifestContractHonored = false;
	}

	// Command-set: collect IDs and detect duplicates + per-record mismatches.
	const evidenceIds = new Set<string>();
	const executionTrees = new Set<string>();
	const evidenceCmds: any[] = [];
	let perCommandDrift = true;
	if (Array.isArray(evObj.commands)) {
		for (const c of evObj.commands) {
			if (c == null) {
				out.malformedEvidenceCommandRows += 1;
				continue;
			}
			if (typeof c !== "object") {
				out.malformedEvidenceCommandRows += 1;
				continue;
			}
			const id = (c as any).id;
			if (typeof id !== "string" || id.length === 0) {
				out.malformedEvidenceCommandRows += 1;
				continue;
			}
			evidenceCmds.push(c);
			evidenceIds.add(id);
			const t = (c as any).tree_oid;
			if (typeof t === "string" && t.length > 0) executionTrees.add(t);

			// CORRECTION11: per-command drift attestation.
			const headBefore = (c as any).head_oid_before;
			const headAfter = (c as any).head_oid_after;
			const treeBefore = (c as any).tree_oid_before;
			const treeAfter = (c as any).tree_oid_after;
			const subjectBefore = (c as any).subject_tree_oid_before;
			const subjectAfter = (c as any).subject_tree_oid_after;
			const allPresent =
				typeof headBefore === "string" &&
				typeof headAfter === "string" &&
				typeof treeBefore === "string" &&
				typeof treeAfter === "string" &&
				typeof subjectBefore === "string" &&
				typeof subjectAfter === "string";
			const allEqual =
				allPresent &&
				headBefore === headAfter &&
				treeBefore === treeAfter &&
				subjectBefore === subjectAfter &&
				headBefore === executionHeadFromEvidence &&
				treeBefore === executionTreeFromEvidence;
			if (!allEqual) perCommandDrift = false;
		}
	}
	out.perCommandDriftChecked = perCommandDrift;

	const executedIds = new Set<string>();
	for (const e of executedCmds) {
		if (e == null || typeof e !== "object") {
			out.malformedExecutedCommandRows += 1;
			continue;
		}
		const id = (e as any).id;
		if (typeof id !== "string" || id.length === 0) {
			out.malformedExecutedCommandRows += 1;
			continue;
		}
		executedIds.add(id);
	}

	const missingExecs: string[] = [];
	const extraInEvidence: string[] = [];
	for (const id of executedIds) if (!evidenceIds.has(id)) missingExecs.push(id);
	for (const id of evidenceIds) if (!executedIds.has(id)) extraInEvidence.push(id);
	out.executionTrees = Array.from(executionTrees);

	const dup = compareCommandRecords(evidenceCmds, executedCmds);
	out.duplicateEvidenceCommandIds = dup.duplicateEvidenceCommandIds;
	out.duplicateExecutedCommandIds = dup.duplicateExecutedCommandIds;
	out.commandRecordMismatches = dup.commandRecordMismatches;

	out.commandSetExact =
		missingExecs.length === 0 &&
		extraInEvidence.length === 0 &&
		out.duplicateEvidenceCommandIds.length === 0 &&
		out.duplicateExecutedCommandIds.length === 0 &&
		out.commandRecordMismatches.length === 0 &&
		out.malformedEvidenceCommandRows === 0 &&
		out.malformedExecutedCommandRows === 0;

	// Execution-tree binding (CORRECTION10): every command row's
	// `tree_oid` must equal the bundle's top-level `execution_tree_oid`,
	// and there must be exactly one distinct value across rows.
	const execTree = executionTrees.size === 1 ? Array.from(executionTrees)[0] : null;
	out.executionTreeBound =
		execTree !== null &&
		executionTreeFromEvidence !== null &&
		execTree === executionTreeFromEvidence;

	// Hash manifest parse + per-line validity.
	const parsed = parseManifest(hashesText);
	out.malformedLines = parsed.malformed;
	out.duplicatePaths = parsed.duplicates;

	const missingFiles: PathDiagnostic[] = [];
	const hashMismatches: HashMismatch[] = [];
	const rejected: PathDiagnostic[] = [];
	const outOfEvDir: PathDiagnostic[] = [];
	for (const [path, expected] of parsed.declared.entries()) {
		const resolved = resolveEvidencePayloadPath(evDirAbs, rootAbs, path);
		if (!resolved.ok) {
			if (resolved.reason === "outside-evidence-dir") {
				outOfEvDir.push({ path, reason: "outside-evidence-dir" });
			} else {
				// resolved.reason is "absolute" | "traversal"
				rejected.push({ path, reason: resolved.reason });
			}
			continue;
		}
		const abs = resolved.abs as string;
		let lst;
		try {
			lst = lstatSync(abs);
		} catch {
			missingFiles.push({ path, reason: "missing" });
			continue;
		}
		if (lst.isSymbolicLink()) {
			missingFiles.push({ path, reason: "symlink" });
			continue;
		}
		if (!lst.isFile()) {
			missingFiles.push({ path, reason: "missing" });
			continue;
		}
		const actual = createHash("sha256").update(readFileSync(abs)).digest("hex");
		if (actual.toLowerCase() !== expected) {
			hashMismatches.push({ path, expected, actual: actual.toLowerCase() });
		}
	}
	out.missingFiles = missingFiles;
	out.hashMismatches = hashMismatches;
	out.rejectedManifestPaths = rejected;
	out.outOfEvidenceDirPaths = outOfEvDir;

	const unexpected = scanUnexpected(evDirAbs, parsed.declared);
	const symlinks: PathDiagnostic[] = [];
	for (const u of unexpected) {
		if (u.reason === "symlink") symlinks.push(u);
		else out.unexpectedFiles.push(u);
	}
	for (const s of symlinks) out.unexpectedFiles.push(s);

	out.hashManifestValid =
		out.malformedLines.length === 0 &&
		out.duplicatePaths.length === 0 &&
		out.missingFiles.length === 0 &&
		out.hashMismatches.length === 0 &&
		out.rejectedManifestPaths.length === 0 &&
		out.outOfEvidenceDirPaths.length === 0;

	// Manifest contract: every path the runner declared as an expected
	// output must be in the manifest (so reviewers can audit it), AND
	// every manifest-declared path must resolve inside the evidence dir
	// (so reviewers can verify hashes).
	if (expectedOutputPaths !== null && out.outOfEvidenceDirPaths.length === 0) {
		const declared = new Set(parsed.declared.keys());
		let allDeclared = true;
		for (const p of expectedOutputPaths) {
			if (!declared.has(p as string)) {
				allDeclared = false;
				break;
			}
		}
		out.manifestContractHonored = allDeclared;
	}

	return out;
}

// ---------- public helpers (exported for tests) -----------------------------

interface ParsedManifest {
	declared: Map<string, string>;
	malformed: MalformedLine[];
	duplicates: DuplicatePath[];
}

export function parseManifest(text: string): ParsedManifest {
	const declared = new Map<string, string>();
	const malformed: MalformedLine[] = [];
	const seenOccurrences = new Map<string, number>();

	if (typeof text !== "string" || text.length === 0) {
		return { declared, malformed, duplicates: [] };
	}

	const lines = text.split("\n");
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (line.trim().length === 0) continue;
		const m = line.match(/^([0-9a-f]{64})[ \t]+(.+?)[ \t]*$/i);
		if (!m) {
			malformed.push({ line: i + 1, content: line.slice(0, 80) });
			continue;
		}
		const sha = m[1].toLowerCase();
		const path = m[2];
		if (declared.has(path)) {
			seenOccurrences.set(path, (seenOccurrences.get(path) ?? 1) + 1);
			continue;
		}
		declared.set(path, sha);
		seenOccurrences.set(path, 1);
	}
	const duplicates: DuplicatePath[] = [];
	for (const [path, occurrences] of seenOccurrences.entries()) {
		if (occurrences > 1) duplicates.push({ path, occurrences });
	}
	return { declared, malformed, duplicates };
}

export type EvidenceLoad = {
	ok: boolean;
	value: unknown;
	error: string | null;
};

export function loadEvidenceFile(path: string): EvidenceLoad {
	if (!existsSync(path)) return { ok: false, value: null, error: "missing" };
	try {
		const text = readFileSync(path, "utf8");
		return { ok: true, value: JSON.parse(text), error: null };
	} catch (e: any) {
		return { ok: false, value: null, error: e?.message ?? String(e) };
	}
}

// ---------- helpers ---------------------------------------------------------

/**
 * Discriminated union with `reason` ∈ the public `PathDiagnostic.reason`
 * vocabulary. There is no separate internal sentinel.
 */
export type ResolveResult =
	| { ok: true; abs: string; reason: null }
	| {
			ok: false;
			abs: null;
			reason: "absolute" | "traversal" | "outside-evidence-dir";
	  };

export function resolveEvidencePayloadPath(
	evDirAbs: string,
	rootAbs: string,
	declared: string,
): ResolveResult {
	if (typeof declared !== "string" || declared.length === 0) {
		return { ok: false, abs: null, reason: "traversal" };
	}
	if (isAbsolute(declared)) {
		return { ok: false, abs: null, reason: "absolute" };
	}

	const normalizedEvDir = resolve(evDirAbs);
	const normalizedRoot = resolve(rootAbs);
	const abs = resolve(normalizedEvDir, declared);

	const relToEvDir = normalizeRelative(relative(normalizedEvDir, abs));
	if (
		relToEvDir === "" ||
		relToEvDir === ".." ||
		relToEvDir.startsWith(`..${sep}`) ||
		isAbsolute(relToEvDir)
	) {
		const relToRoot = normalizeRelative(relative(normalizedRoot, abs));
		if (
			relToRoot === "" ||
			relToRoot === ".." ||
			relToRoot.startsWith(`..${sep}`) ||
			isAbsolute(relToRoot)
		) {
			return { ok: false, abs: null, reason: "traversal" };
		}
		return { ok: false, abs: null, reason: "outside-evidence-dir" };
	}
	return { ok: true, abs, reason: null };
}

function scanUnexpected(
	evDirAbs: string,
	declared: Map<string, string>,
): PathDiagnostic[] {
	if (!existsSync(evDirAbs)) return [];
	const out: PathDiagnostic[] = [];
	const declaredInside = new Set<string>();
	for (const p of declared.keys()) {
		declaredInside.add(normalizeRelative(p));
	}
	walk(evDirAbs, (abs, lst) => {
		if (lst.isSymbolicLink()) {
			out.push({ path: normalizeRelative(relative(evDirAbs, abs)), reason: "symlink" });
			return;
		}
		if (!lst.isFile()) return;
		const rel = normalizeRelative(relative(evDirAbs, abs));
		if (rel.length === 0) return;
		if (CONTROL_FILES.has(rel)) return;
		if (!declaredInside.has(rel)) {
			out.push({ path: rel, reason: "unexpected" });
		}
	});
	return out;
}

function walk(
	absDir: string,
	visit: (abs: string, lst: import("node:fs").Stats) => void,
): void {
	let entries: string[];
	try {
		entries = readdirSync(absDir);
	} catch {
		return;
	}
	for (const name of entries) {
		const child = join(absDir, name);
		let lst;
		try {
			lst = lstatSync(child);
		} catch {
			continue;
		}
		if (lst.isDirectory()) {
			if (name === "node_modules" || name === ".git") continue;
			walk(child, visit);
		} else {
			visit(child, lst);
		}
	}
}

function normalizeRelative(p: string): string {
	return p.split(sep).join("/");
}

interface CompareResult {
	duplicateEvidenceCommandIds: DuplicatePath[];
	duplicateExecutedCommandIds: DuplicatePath[];
	commandRecordMismatches: CommandRecordMismatch[];
}

function compareCommandRecords(
	evidenceCmds: any[],
	executedCmds: any[],
): CompareResult {
	const duplicateEvidenceCommandIds = collectDuplicateIds(evidenceCmds);
	const duplicateExecutedCommandIds = collectDuplicateIds(executedCmds);

	const evidenceById = new Map<string, any>();
	for (const c of evidenceCmds) {
		if (c && typeof c.id === "string") evidenceById.set(c.id, c);
	}
	const executedById = new Map<string, any>();
	for (const c of executedCmds) {
		if (c && typeof c.id === "string") executedById.set(c.id, c);
	}

	const commandRecordMismatches: CommandRecordMismatch[] = [];
	for (const [id, ev] of evidenceById.entries()) {
		const ex = executedById.get(id);
		if (!ex) continue;
		const fields: string[] = [];
		const evSnap: Record<string, unknown> = {};
		const exSnap: Record<string, unknown> = {};
		for (const f of RECORD_COMPARE_FIELDS) {
			const a = (ev as any)[f];
			const b = (ex as any)[f];
			if (a === b) continue;
			if (a == null && b == null) continue;
			fields.push(f);
			evSnap[f] = a ?? null;
			exSnap[f] = b ?? null;
		}
		if (fields.length > 0) {
			commandRecordMismatches.push({ id, fields, evidence: evSnap, executed: exSnap });
		}
	}

	return {
		duplicateEvidenceCommandIds,
		duplicateExecutedCommandIds,
		commandRecordMismatches,
	};
}

function collectDuplicateIds(items: any[]): DuplicatePath[] {
	const seen = new Map<string, number>();
	for (const c of items) {
		if (c && typeof c.id === "string") {
			seen.set(c.id, (seen.get(c.id) ?? 0) + 1);
		}
	}
	const dupes: DuplicatePath[] = [];
	for (const [id, occurrences] of seen.entries()) {
		if (occurrences > 1) dupes.push({ path: id, occurrences });
	}
	return dupes;
}
