#!/usr/bin/env bun
/**
 * ACT-CLINEMM-FORK-BASELINE01-CORRECTION13 — verification runner.
 *
 * The runner binds every command to one execution HEAD/tree and one filtered
 * subject tree, samples path-aware worktree cleanliness around every command,
 * and builds evidence transactionally in a fresh sibling staging directory.
 * The canonical bundle is replaced only after the staged bundle passes the
 * same structural `checkEvidence()` validation used by the renderer.
 *
 * CORRECTION13: the staged bundle is now self-contained — the executed-command
 * result document lives inside the staging directory as
 * `verification-results.json` and is hash-verified by `checkEvidence()`. The
 * tracked mirror at `factory/inventories/verification-results.json` is only
 * refreshed after the canonical swap succeeds. The `fs.watch`-based
 * tracked-input observation is demoted from a proof-bearing closure dimension
 * to a hint; `perCommandInputsClean` is removed from the conjunction.
 */

import { spawn, spawnSync } from "node:child_process";
import { createHash, randomBytes } from "node:crypto";
import {
	existsSync,
	lstatSync,
	mkdirSync,
	readFileSync,
	realpathSync,
	renameSync,
	rmSync,
	watch,
	writeFileSync,
	type FSWatcher,
} from "node:fs";
import { basename, dirname, isAbsolute, join, posix, relative, resolve, sep } from "node:path";

import {
	checkEvidence,
	isEvidenceOk,
	loadEvidenceFile,
	loadNativeProbesFromEvidence,
	NATIVE_PROBES_BUNDLE_PATH,
	NATIVE_PROBES_INVENTORY_PATH,
	resolveEvidencePayloadPath,
	type ExecutionIdentityDerivation,
} from "./baseline-closure";
import {
	collectNativeProbesInventory,
	writeInventory,
	type NativeProbesInventory,
} from "./collect-native-probes";
import { parsePorcelainV1Z } from "./git-status";
import { canonicalStreamPaths, NATIVE_PROBE_DEFINITIONS } from "./native-probes";
import { computeFilteredSubjectTreeOid, SUBJECT_TREE_EXCLUDES } from "./subject-tree";

const ACT_ID = "ACT-CLINEMM-FORK-BASELINE01";
const RESULTS_JSON = "factory/inventories/verification-results.json";
const EVIDENCE_PARENT = ".factory/evidence";
const DETACHED_DIR = `${EVIDENCE_PARENT}/${ACT_ID}`;
const OID_PATTERN = /^[0-9a-f]{40}$/;
const SAFE_COMMAND_ID = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;

/**
 * Repository-relative files intentionally regenerated by this workflow.
 * This list participates only in worktree cleanliness. It is never copied to
 * evidence.json and is unrelated to manifest payload completeness.
 */
export const EXPECTED_REPOSITORY_OUTPUT_PATHS: ReadonlyArray<string> = [
	RESULTS_JSON,
	"factory/inventories/environment.json",
	"factory/inventories/repository.json",
	"factory/inventories/workspaces.json",
	"factory/inventories/native-probes.json",
	"factory/inventories/network-listener-candidates.csv",
	"factory/inventories/privileged-sink-candidates.csv",
	"factory/baselines/file-size-summary.json",
	"factory/baselines/file-size.csv",
	"factory/baselines/exact-duplicates.json",
	"docs/factory/baseline-report.md",
];

const REQUIRED_RUNNER_SOURCE_PATHS: ReadonlyArray<string> = [
	"factory/scripts/run-verification.ts",
	"factory/scripts/baseline-closure.ts",
	"factory/scripts/git-status.ts",
	"factory/scripts/subject-tree.ts",
];

interface RunnerArgs {
	finalize: boolean;
	onlyFilter: string | null;
	skipFilter: Set<string> | null;
	timeoutMs: number;
	probeInventoryPath: string | null;
}

interface VerificationCommand {
	id: string;
	class: string;
	host_support: string[];
	requires_gui?: boolean;
	working_directory?: string;
	argv?: unknown[];
	shell_command?: string;
	command?: string;
	[key: string]: unknown;
}

interface ExecutionIdentity {
	head: string;
	tree: string;
	subject: string;
}

type FailureClass =
	| "FORK-INTRODUCED"
	| "UPSTREAM-REPRODUCIBLE"
	| "ENVIRONMENTAL"
	| "CREDENTIAL-REQUIRED"
	| "NETWORK-DEPENDENT"
	| "HOST-UNSUPPORTED"
	| "NONDETERMINISTIC"
	| "TIMEOUT"
	| "TOOLCHAIN-DRIFT"
	| "UNKNOWN";

interface ExecResult {
	id: string;
	status: "pass" | "fail";
	started_at: string;
	finished_at: string;
	duration_ms: number;
	exit_code: number | null;
	signal: string | null;
	timeout: boolean;
	stdout_sha256: string;
	stderr_sha256: string;
	stdout_path: string;
	stderr_path: string;
	metadata_path: string;
	head_oid: string;
	tree_oid: string;
	head_oid_before: string;
	head_oid_after: string;
	tree_oid_before: string;
	tree_oid_after: string;
	subject_tree_oid_before: string;
	subject_tree_oid_after: string;
	// CORRECTION13: rename the per-command transient claim to an observation
	// of the fs.watch-backed monitor. It is NOT proof that no transient
	// modification occurred; downstream must treat it as advisory.
	tracked_input_change_observed: boolean;
	tracked_input_monitor_degraded: boolean;
	observed_tracked_input_paths: string[];
	unexpected_paths_after: string[];
	environment_sha256: string;
	failure_classification: FailureClass | null;
	notes: string;
}

interface SkippedResult {
	id: string;
	status: "skip" | "unavailable";
	started_at: string;
	finished_at: string;
	duration_ms: 0;
	exit_code: null;
	signal: null;
	timeout: false;
	stdout_sha256: string;
	stderr_sha256: string;
	head_oid: string;
	tree_oid: string;
	environment_sha256: string;
	failure_classification: null;
	notes: string;
}

interface CleanlinessSample {
	clean: boolean;
	unexpected: string[];
}

interface ResolvedCommand {
	argv: string[];
}

interface ProcessOutcome {
	code: number | null;
	signal: NodeJS.Signals | null;
	timedOut: boolean;
	stdout: string;
	stderr: string;
	spawnError: Error | null;
}

interface PayloadPaths {
	stdoutRel: string;
	stderrRel: string;
	metadataRel: string;
	stdoutAbs: string;
	stderrAbs: string;
	metadataAbs: string;
}

interface PassResultDocument {
	schema_version: number;
	host: string;
	executed_at: string;
	executed_commands: ExecResult[];
	skipped_commands: SkippedResult[];
	commands: Array<Record<string, unknown>>;
}

const SECRET_PATTERNS: RegExp[] = [
	/AKIA[0-9A-Z]{16}/g,
	/sk-[A-Za-z0-9_-]{20,}/g,
	/ghp_[A-Za-z0-9]{20,}/g,
	/xox[baprs]-[0-9A-Za-z-]{20,}/g,
	/-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g,
	/Bearer\s+[A-Za-z0-9._-]{20,}/g,
];

function repoRoot(): string {
	const result = spawnSync("git", ["rev-parse", "--show-toplevel"], {
		cwd: process.cwd(),
		encoding: "utf8",
		stdio: ["ignore", "pipe", "pipe"],
	});
	if (result.status !== 0) {
		throw new Error(`git rev-parse --show-toplevel failed: ${(result.stderr ?? "").trim()}`);
	}
	return (result.stdout ?? "").trim();
}

/**
 * CORRECTION20: the `--probe-inventory-path <file>` argument is a
 * TEST-ONLY escape hatch. Production runners always execute real probes
 * via `collectNativeProbesInventory`. To make sure no production
 * invocation can accidentally consume a hand-authored fixture
 * inventory, the runner requires the `FACTORY_TEST_FIXTURE_MODE=1`
 * environment flag whenever this argument is present; otherwise the
 * runner refuses the argument and exits with a hard error. The fixture
 * tests set the flag in their child-process env so this guard never
 * trips in CI, but a stray production call (where the env var is not
 * set) now fails closed. The constant is declared BEFORE the
 * `parseArgs` callsite so `fixtureModeEnabled()` does not hit a
 * temporal-dead-zone ReferenceError when the runner first loads.
 */
const FACTORY_TEST_FIXTURE_MODE_ENV = "FACTORY_TEST_FIXTURE_MODE";

function fixtureModeEnabled(): boolean {
	return process.env[FACTORY_TEST_FIXTURE_MODE_ENV] === "1";
}

const ROOT = repoRoot();
const CANONICAL_EVIDENCE_DIR = join(ROOT, DETACHED_DIR);
const ARGS = parseArgs(process.argv.slice(2));
const ENVIRONMENT_SHA256 = envSha();

function parseArgs(argv: string[]): RunnerArgs {
	const valueAfter = (flag: string): string | null => {
		const index = argv.indexOf(flag);
		if (index < 0) return null;
		const value = argv[index + 1];
		if (!value || value.startsWith("--")) throw new Error(`${flag} requires a value`);
		return value;
	};
	const timeoutText = valueAfter("--timeout-ms");
	const timeoutMs = timeoutText === null ? 600_000 : Number.parseInt(timeoutText, 10);
	if (!Number.isSafeInteger(timeoutMs) || timeoutMs <= 0) {
		throw new Error(`--timeout-ms must be a positive integer; received ${timeoutText}`);
	}
	const onlyFilter = valueAfter("--only");
	const skipText = valueAfter("--skip");
	const probeInventoryPath = valueAfter("--probe-inventory-path");
	if (probeInventoryPath !== null && !fixtureModeEnabled()) {
		throw new Error(
			`--probe-inventory-path is a test-fixture escape hatch; the runner refuses it unless ${FACTORY_TEST_FIXTURE_MODE_ENV}=1 is set in the environment. Production runs always go through collectNativeProbesInventory().`,
		);
	}
	return {
		finalize: argv.includes("--finalize-evidence"),
		onlyFilter,
		skipFilter: skipText === null ? null : new Set(skipText.split(",").filter(Boolean)),
		timeoutMs,
		probeInventoryPath,
	};
}

function redact(value: string): string {
	let redacted = value;
	for (const pattern of SECRET_PATTERNS) redacted = redacted.replace(pattern, "[REDACTED]");
	return redacted;
}

function envSha(): string {
	const bunVersion = spawnSync("bun", ["--version"], { encoding: "utf8" });
	const environment = {
		platform: process.platform,
		arch: process.arch,
		nodeVersion: process.version,
		bunVersion: bunVersion.status === 0 ? (bunVersion.stdout ?? "").trim() : "unknown",
		envVarNames: Object.keys(process.env).sort(),
		ci: process.env.CI ?? null,
		githubActions: process.env.GITHUB_ACTIONS ?? null,
		shell: process.env.SHELL ?? null,
	};
	return sha256(JSON.stringify(environment));
}

function sha256(value: Buffer | string): string {
	return createHash("sha256").update(value).digest("hex");
}

function runGitText(args: string[]): { status: number | null; stdout: string; stderr: string } {
	const result = spawnSync("git", args, {
		cwd: ROOT,
		encoding: "utf8",
		stdio: ["ignore", "pipe", "pipe"],
	});
	return {
		status: result.status,
		stdout: (result.stdout ?? "").toString(),
		stderr: (result.stderr ?? "").toString(),
	};
}

function revParseVerify(expression: string): string | null {
	const result = runGitText(["rev-parse", "--verify", "--end-of-options", expression]);
	if (result.status !== 0) return null;
	const oid = result.stdout.trim();
	return OID_PATTERN.test(oid) ? oid : null;
}

function headTreeNow(): { head: string; tree: string } {
	const head = revParseVerify("HEAD^{commit}");
	const tree = revParseVerify("HEAD^{tree}");
	if (!head || !tree) throw new Error("EXECUTION_IDENTITY_INVALID: HEAD or HEAD^{tree} did not resolve");
	return { head, tree };
}

function captureExecutionIdentity(): ExecutionIdentity {
	const { head, tree } = headTreeNow();
	const subject = computeFilteredSubjectTreeOid(ROOT);
	if (!subject) {
		throw new Error("SUBJECT_TREE_COMPUTATION_FAILED: filtered tree could not be computed");
	}
	return { head, tree, subject };
}

/** Runner assertion retained in evidence; the renderer verifies independently. */
function verifyExecutionIdentityShape(head: string, tree: string): boolean {
	if (!OID_PATTERN.test(head) || !OID_PATTERN.test(tree)) return false;
	const resolvedHead = revParseVerify(`${head}^{commit}`);
	const resolvedTree = revParseVerify(`${tree}^{tree}`);
	const derivedTree = revParseVerify(`${head}^{tree}`);
	return resolvedHead !== null && resolvedTree !== null && derivedTree === tree;
}

function deriveExecutionIdentityForLocalCheck(head: string, tree: string): ExecutionIdentityDerivation {
	return {
		executionHeadExists: revParseVerify(`${head}^{commit}`) !== null,
		executionTreeExists: revParseVerify(`${tree}^{tree}`) !== null,
		derivedTreeOid: revParseVerify(`${head}^{tree}`),
	};
}

function isExpectedRepositoryOutput(path: string): boolean {
	return EXPECTED_REPOSITORY_OUTPUT_PATHS.includes(normalizeGitPath(path));
}

/**
 * Uses the machine-readable NUL protocol and intentionally does not pass
 * `--ignored`: ignored files are outside ordinary worktree cleanliness.
 */
export function worktreeInputsClean(): CleanlinessSample {
	const result = spawnSync(
		"git",
		[
			"-c",
			"status.showUntrackedFiles=all",
			"status",
			"--porcelain=v1",
			"-z",
			"--untracked-files=all",
		],
		{
			cwd: ROOT,
			stdio: ["ignore", "pipe", "pipe"],
			maxBuffer: 32 * 1024 * 1024,
		},
	);
	if (result.status !== 0) {
		const stderr = (result.stderr ?? Buffer.alloc(0)).toString("utf8").trim();
		return { clean: false, unexpected: [`<git-status-error:${stderr || "unknown"}>`] };
	}
	try {
		const unexpected = new Set<string>();
		for (const entry of parsePorcelainV1Z(result.stdout ?? Buffer.alloc(0))) {
			for (const path of [entry.path, entry.originalPath]) {
				if (path !== null && !isExpectedRepositoryOutput(path)) {
					unexpected.add(normalizeGitPath(path));
				}
			}
		}
		return { clean: unexpected.size === 0, unexpected: [...unexpected].sort() };
	} catch (error) {
		return {
			clean: false,
			unexpected: [`<git-status-parse-error:${error instanceof Error ? error.message : String(error)}>`],
		};
	}
}

function normalizeGitPath(path: string): string {
	return path.split(sep).join("/");
}

function hostClass(): string {
	const platform = process.platform;
	const arch = process.arch;
	if (platform === "darwin" && arch === "arm64") return "darwin-arm64";
	if (platform === "linux" && arch === "x64") return "linux-x64";
	if (platform === "win32" && arch === "x64") return "windows-x64";
	if (platform === "linux" && arch === "arm64") return "linux-arm64";
	if (platform === "win32" && arch === "arm64") return "windows-arm64";
	return `${platform}-${arch}`;
}

function verifyRunnerSourceBound(): void {
	const expectedRunner = join(ROOT, "factory/scripts/run-verification.ts");
	if (
		!existsSync(expectedRunner) ||
		realpathSync(import.meta.path) !== realpathSync(expectedRunner)
	) {
		throw new Error(
			`RUNNER_SOURCE_NOT_BOUND: invoked ${import.meta.path} outside repository ${ROOT}`,
		);
	}
	for (const path of REQUIRED_RUNNER_SOURCE_PATHS) {
		const absolute = join(ROOT, ...path.split("/"));
		if (!existsSync(absolute) || !lstatSync(absolute).isFile() || lstatSync(absolute).isSymbolicLink()) {
			throw new Error(`RUNNER_SOURCE_NOT_BOUND: ${path} is missing, non-regular, or symlinked`);
		}
		const tracked = runGitText(["ls-files", "--error-unmatch", "--", path]);
		const committed = runGitText(["cat-file", "-e", `HEAD:${path}`]);
		if (tracked.status !== 0 || committed.status !== 0) {
			throw new Error(`RUNNER_SOURCE_NOT_BOUND: ${path} is not tracked at the execution HEAD`);
		}
	}
}

function validateCommands(commands: unknown): asserts commands is VerificationCommand[] {
	if (!Array.isArray(commands)) throw new Error("verification.json commands must be an array");
	const seen = new Set<string>();
	for (const [index, command] of commands.entries()) {
		if (command === null || typeof command !== "object") {
			throw new Error(`verification command at index ${index} is not an object`);
		}
		const value = command as Record<string, unknown>;
		if (typeof value.id !== "string" || !SAFE_COMMAND_ID.test(value.id)) {
			throw new Error(`INVALID_EVIDENCE_PATH: command id ${JSON.stringify(value.id)} is not path-safe`);
		}
		if (seen.has(value.id)) throw new Error(`duplicate verification command id: ${value.id}`);
		seen.add(value.id);
		if (typeof value.class !== "string") throw new Error(`command ${value.id} has no class`);
		if (!Array.isArray(value.host_support) || !value.host_support.every((h) => typeof h === "string")) {
			throw new Error(`command ${value.id} has invalid host_support`);
		}
	}
}

function resolveArgv(command: VerificationCommand): ResolvedCommand {
	if (Array.isArray(command.argv) && command.argv.length > 0) {
		return { argv: command.argv.map((value) => String(value)) };
	}
	if (typeof command.shell_command === "string" && command.shell_command.length > 0) {
		return { argv: ["/bin/sh", "-c", command.shell_command] };
	}
	if (typeof command.command === "string" && command.command.length > 0) {
		const parts = command.command.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g) ?? [];
		return {
			argv: parts.map((part) => part.replace(/^(?:"(.*)"|'(.*)')$/, "$1$2")),
		};
	}
	throw new Error(`command ${command.id} has no executable form (argv/shell_command/command)`);
}

function resolveWorkingDirectory(command: VerificationCommand): string {
	const declared = command.working_directory ?? ".";
	if (typeof declared !== "string" || declared.length === 0 || isAbsolute(declared)) {
		throw new Error(`command ${command.id} has invalid working_directory`);
	}
	const absolute = resolve(ROOT, declared);
	const rel = relative(ROOT, absolute);
	if (rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel)) {
		throw new Error(`command ${command.id} working_directory escapes the repository`);
	}
	return absolute;
}

function payloadPaths(evidenceDir: string, commandId: string): PayloadPaths {
	if (!SAFE_COMMAND_ID.test(commandId)) {
		throw new Error(`INVALID_EVIDENCE_PATH: command id ${JSON.stringify(commandId)} is not path-safe`);
	}
	const stdoutRel = posix.join("commands", `${commandId}.stdout`);
	const stderrRel = posix.join("commands", `${commandId}.stderr`);
	const metadataRel = posix.join("commands", `${commandId}.metadata.json`);
	return {
		stdoutRel,
		stderrRel,
		metadataRel,
		stdoutAbs: join(evidenceDir, ...stdoutRel.split("/")),
		stderrAbs: join(evidenceDir, ...stderrRel.split("/")),
		metadataAbs: join(evidenceDir, ...metadataRel.split("/")),
	};
}

function listTrackedInputPaths(): string[] {
	const result = spawnSync("git", ["ls-files", "-z"], {
		cwd: ROOT,
		stdio: ["ignore", "pipe", "pipe"],
		maxBuffer: 32 * 1024 * 1024,
	});
	if (result.status !== 0) throw new Error("git ls-files -z failed while preparing command monitor");
	return (result.stdout ?? Buffer.alloc(0))
		.toString("utf8")
		.split("\0")
		.filter(Boolean)
		.map(normalizeGitPath)
		.filter((path) => !isExpectedRepositoryOutput(path));
}

interface TrackedInputObservation {
	touched: string[];
	degraded: boolean;
}

interface TrackedInputMonitor {
	stop(): TrackedInputObservation;
}

function startTrackedInputMonitor(paths: string[]): TrackedInputMonitor {
	const tracked = new Set(paths);
	const before = new Map<string, string>();
	for (const path of paths) before.set(path, fingerprint(path));
	const touched = new Set<string>();
	let watcher: FSWatcher | null = null;
	let degraded = false;
	try {
		watcher = watch(ROOT, { recursive: true}, (_event, filename) => {
			if (filename === null) {
				degraded = true;
				return;
			}
			const path = normalizeGitPath(Buffer.isBuffer(filename) ? filename.toString("utf8") : filename);
			if (tracked.has(path)) touched.add(path);
		});
		watcher.on("error", () => {
			degraded = true;
			watcher?.close();
		});
	} catch {
		degraded = true;
	}
	let stopped = false;
	let finalObservation: TrackedInputObservation | null = null;
	return {
		stop(): TrackedInputObservation {
			if (stopped && finalObservation) return finalObservation;
			stopped = true;
			watcher?.close();
			for (const path of paths) {
				if (before.get(path) !== fingerprint(path)) touched.add(path);
			}
			finalObservation = { touched: [...touched].sort(), degraded };
			return finalObservation;
		},
	};
}

function fingerprint(path: string): string {
	try {
		const value = lstatSync(join(ROOT, ...path.split("/")), {bigint: true});
		return [
			value.dev,
			value.ino,
			value.mode,
			value.size,
			value.mtimeNs,
			value.ctimeNs,
		].join(":");
	} catch {
		return "<missing>";
	}
}

async function executeCommand(
	command: VerificationCommand,
	bundleIdentity: ExecutionIdentity,
	evidenceDir: string,
	trackedInputs: string[],
): Promise<ExecResult> {
	const paths = payloadPaths(evidenceDir, command.id);
	mkdirSync(dirname(paths.stdoutAbs), {recursive: true});

	const stateBefore = captureExecutionIdentity();
	assertIdentityPinned(stateBefore, bundleIdentity, `REPOSITORY_DRIFT_BEFORE_COMMAND: ${command.id}`);

	const monitor = startTrackedInputMonitor(trackedInputs);
	const cleanlinessBefore = worktreeInputsClean();
	if (!cleanlinessBefore.clean) {
		monitor.stop();
		throw new Error(
			`WORKTREE_INPUTS_DIRTY_BEFORE_COMMAND: ${command.id}: ${cleanlinessBefore.unexpected.join(", ")}`,
		);
	}

	const startedAt = new Date();
	let outcome: ProcessOutcome;
	try {
		const resolved = resolveArgv(command);
		const workingDirectory = resolveWorkingDirectory(command);
		outcome = await runProcess(resolved, workingDirectory);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		outcome = {
			code: null,
			signal: null,
			timedOut: false,
			stdout: "",
			stderr: `command setup error: ${message}\n`,
			spawnError: error instanceof Error ? error : new Error(message),
		};
	}

	const cleanlinessAfterRaw = worktreeInputsClean();
	const monitorObservation = monitor.stop();
	// CORRECTION13: only the post-command git status sample contributes
	// to the proof-bearing `unexpected_paths_after` field. The transient
	// monitor observations are kept separate as advisory hints.
	const unexpectedAfter = [...cleanlinessAfterRaw.unexpected].sort();
	const trackedInputChangeObserved = monitorObservation.touched.length > 0;

	let stateAfter = bundleIdentity;
	let identityCaptureError: Error | null = null;
	try {
		stateAfter = captureExecutionIdentity();
	} catch (error) {
		identityCaptureError = error instanceof Error ? error : new Error(String(error));
	}

	const finishedAt = new Date();
	// A spawn failure never sees a real signal because the process never
	// existed. Normalize the recorded signal to null so the validator's
	// relational invariant (`signal` null + status fail + exit_code=-1)
	// is well-formed.
	if (outcome.spawnError !== null) {
		outcome.signal = null;
	}
	const status: ExecResult["status"] =
		outcome.spawnError === null && !outcome.timedOut && outcome.code === 0 ? "pass" : "fail";
	const classification =
		status === "pass"
			? null
			: outcome.timedOut
				? "TIMEOUT"
				: classifyFailure(command, outcome.code, outcome.signal, outcome.stdout, outcome.stderr);
	const stdoutBytes = Buffer.from(outcome.stdout, "utf8");
	const stderrBytes = Buffer.from(outcome.stderr, "utf8");
	const result: ExecResult = {
		id: command.id,
		status,
		started_at: startedAt.toISOString(),
		finished_at: finishedAt.toISOString(),
		duration_ms: finishedAt.getTime() - startedAt.getTime(),
		exit_code: outcome.spawnError ? (outcome.code ?? -1) : outcome.code,
		signal: outcome.signal,
		timeout: outcome.timedOut,
		stdout_sha256: sha256(stdoutBytes),
		stderr_sha256: sha256(stderrBytes),
		stdout_path: paths.stdoutRel,
		stderr_path: paths.stderrRel,
		metadata_path: paths.metadataRel,
		head_oid: bundleIdentity.head,
		tree_oid: bundleIdentity.tree,
		head_oid_before: stateBefore.head,
		head_oid_after: stateAfter.head,
		tree_oid_before: stateBefore.tree,
		tree_oid_after: stateAfter.tree,
		subject_tree_oid_before: stateBefore.subject,
		subject_tree_oid_after: stateAfter.subject,
		tracked_input_change_observed: trackedInputChangeObserved,
		tracked_input_monitor_degraded: monitorObservation.degraded,
		observed_tracked_input_paths: monitorObservation.touched,
		unexpected_paths_after: unexpectedAfter,
		environment_sha256: ENVIRONMENT_SHA256,
		failure_classification: classification,
		notes: buildNotes(command, outcome),
	};

	// Always materialize all three payloads, including setup/spawn failures.
	atomicWriteFile(paths.stdoutAbs, stdoutBytes);
	atomicWriteFile(paths.stderrAbs, stderrBytes);
	atomicWriteFile(paths.metadataAbs, JSON.stringify(result, null, "\t") + "\n");

	if (identityCaptureError) {
		throw new Error(`REPOSITORY_DRIFT_AFTER_COMMAND: ${command.id}: ${identityCaptureError.message}`);
	}
	assertIdentityPinned(stateAfter, bundleIdentity, `REPOSITORY_DRIFT_AFTER_COMMAND: ${command.id}`);
	if (!cleanlinessAfterRaw.clean) {
		throw new Error(
			`WORKTREE_INPUTS_DIRTY_AFTER_COMMAND: ${command.id}: ${unexpectedAfter.join(", ")}`,
		);
	}
	return result;
}

function assertIdentityPinned(actual: ExecutionIdentity, expected: ExecutionIdentity, prefix: string): void {
	if (
		actual.head !== expected.head ||
		actual.tree !== expected.tree ||
		actual.subject !== expected.subject
	) {
		throw new Error(
			`${prefix}: expected head=${expected.head} tree=${expected.tree} subject=${expected.subject}; ` +
				`observed head=${actual.head} tree=${actual.tree} subject=${actual.subject}`,
		);
	}
}

async function runProcess(resolved: ResolvedCommand, cwd: string): Promise<ProcessOutcome> {
	return await new Promise((resolvePromise) => {
		let child;
		try {
			child = spawn(resolved.argv[0]!, resolved.argv.slice(1), {
				cwd,
				stdio: ["ignore", "pipe", "pipe"],
				detached: true,
				env: process.env,
				shell: false,
			});
		} catch (error) {
			const spawnError = error instanceof Error ? error : new Error(String(error));
			resolvePromise({
				code: -1,
				signal: null,
				timedOut: false,
				stdout: "",
				stderr: `spawn error: ${spawnError.message}\n`,
				spawnError,
			});
			return;
		}

		const stdoutChunks: Buffer[] = [];
		const stderrChunks: Buffer[] = [];
		child.stdout?.on("data", (chunk: Buffer | string) => stdoutChunks.push(Buffer.from(chunk)));
		child.stderr?.on("data", (chunk: Buffer | string) => stderrChunks.push(Buffer.from(chunk)));

		let timedOut = false;
		let spawnError: Error | null = null;
		let settled = false;
		let killTimer: ReturnType<typeof setTimeout> | null = null;
		const timeout = setTimeout(() => {
			timedOut = true;
			killProcessGroup(child.pid, "SIGTERM");
			killTimer = setTimeout(() => killProcessGroup(child.pid, "SIGKILL"), 5_000);
			killTimer.unref();
		}, ARGS.timeoutMs);

		const finish = (code: number | null, signal: NodeJS.Signals | null): void => {
			if (settled) return;
			settled = true;
			clearTimeout(timeout);
			if (killTimer) clearTimeout(killTimer);
			const stdout = redact(Buffer.concat(stdoutChunks).toString("utf8"));
			let stderr = redact(Buffer.concat(stderrChunks).toString("utf8"));
			if (spawnError && !stderr.includes(spawnError.message)) {
				stderr += `${stderr.length > 0 && !stderr.endsWith("\n") ? "\n" : ""}spawn error: ${spawnError.message}\n`;
			}
			resolvePromise({ code, signal, timedOut, stdout, stderr, spawnError });
		};

		child.once("error", (error) => {
			spawnError = error;
			queueMicrotask(() => finish(-1, null));
		});
		child.once("close", finish);
	});
}

function killProcessGroup(pid: number | undefined, signal: NodeJS.Signals): void {
	if (pid === undefined) return;
	try {
		process.kill(-pid, signal);
	} catch {
		try {
			process.kill(pid, signal);
		} catch {
			// Process already exited.
		}
	}
}

function classifyFailure(
	_command: VerificationCommand,
	code: number | null,
	signal: NodeJS.Signals | null,
	stdout: string,
	stderr: string,
): FailureClass {
	const text = `${stdout}\n${stderr}`.toLowerCase();
	if (/no matching workspace|cannot find module|@cline\/\S+ not found|workspace not found/i.test(text)) {
		return "ENVIRONMENTAL";
	}
	if (/network|fetch failed|enotfound|econnrefused|getaddrinfo|tls handshake/i.test(text)) {
		return "NETWORK-DEPENDENT";
	}
	if (/credential|api.?key|unauthorized|forbidden|401|403|authentication/i.test(text)) {
		return "CREDENTIAL-REQUIRED";
	}
	if (signal === "SIGSEGV" || /segmentation fault|out of memory/i.test(text)) {
		return "ENVIRONMENTAL";
	}
	if (/timeout|timed out/i.test(text)) return "TIMEOUT";
	if (code === 127 || /command not found/i.test(text)) return "ENVIRONMENTAL";
	return "UNKNOWN";
}

function buildNotes(command: VerificationCommand, outcome: ProcessOutcome): string {
	const invocation = Array.isArray(command.argv)
		? command.argv.join(" ")
		: (command.shell_command ?? command.command ?? "");
	const tail = outcome.stderr.length > 400 ? `...${outcome.stderr.slice(-400)}` : outcome.stderr;
	return [
		`argv: ${invocation}`,
		`exit_code: ${outcome.code}`,
		`signal: ${outcome.signal ?? ""}`,
		`timeout: ${outcome.timedOut}`,
		`stderr_tail: ${tail}`,
	].join("\n");
}

function buildSkipped(command: VerificationCommand, status: SkippedResult["status"], notes: string): SkippedResult {
	const { head, tree } = headTreeNow();
	const now = new Date().toISOString();
	return {
		id: command.id,
		status,
		started_at: now,
		finished_at: now,
		duration_ms: 0,
		exit_code: null,
		signal: null,
		timeout: false,
		stdout_sha256: sha256(""),
		stderr_sha256: sha256(""),
		head_oid: head,
		tree_oid: tree,
		environment_sha256: ENVIRONMENT_SHA256,
		failure_classification: null,
		notes,
	};
}

function createStagingDirectory(): string {
	const parent = join(ROOT, EVIDENCE_PARENT);
	mkdirSync(parent, {recursive: true});
	const nonce = `${process.pid}-${Date.now()}-${randomBytes(6).toString("hex")}`;
	const staging = join(parent, `.${ACT_ID}-staging-${nonce}`);
	mkdirSync(join(staging, "commands"), {recursive: true});
	return staging;
}

function atomicWriteFile(path: string, content: string | Buffer): void {
	mkdirSync(dirname(path), {recursive: true});
	const temp = join(
		dirname(path),
		`.${basename(path)}.tmp-${process.pid}-${randomBytes(6).toString("hex")}`,
	);
	try {
		writeFileSync(temp, content);
		renameSync(temp, path);
	} finally {
		rmSync(temp, {force: true});
	}
}

function replaceCanonicalBundle(stagingDir: string): void {
	const parent = dirname(CANONICAL_EVIDENCE_DIR);
	const backup = join(
		parent,
		`.${ACT_ID}-previous-${process.pid}-${Date.now()}-${randomBytes(4).toString("hex")}`,
	);
	let previousMoved = false;
	try {
		if (existsSync(CANONICAL_EVIDENCE_DIR)) {
			renameSync(CANONICAL_EVIDENCE_DIR, backup);
			previousMoved = true;
		}
		renameSync(stagingDir, CANONICAL_EVIDENCE_DIR);
	} catch (error) {
		if (!existsSync(CANONICAL_EVIDENCE_DIR) && previousMoved && existsSync(backup)) {
			renameSync(backup, CANONICAL_EVIDENCE_DIR);
		}
		throw error;
	}
	if (previousMoved) rmSync(backup, {recursive: true, force: true});
}

async function runPass(commands: VerificationCommand[], label: string): Promise<void> {
	const stagingDir = createStagingDirectory();
	try {
		const identityBefore = captureExecutionIdentity();
		if (!verifyExecutionIdentityShape(identityBefore.head, identityBefore.tree)) {
			throw new Error("EXECUTION_IDENTITY_INVALID: runner could not verify head/tree object relationship");
		}
		const preflight = worktreeInputsClean();
		if (!preflight.clean) {
			throw new Error(`WORKTREE_INPUTS_DIRTY_BEFORE: ${preflight.unexpected.join(", ")}`);
		}

		const trackedInputs = listTrackedInputPaths();
		const host = hostClass();
		const skipped: SkippedResult[] = [];
		const executed: ExecResult[] = [];
		let attemptCount = 0;

		for (const command of commands) {
			if (ARGS.onlyFilter && command.id !== ARGS.onlyFilter) {
				skipped.push(buildSkipped(command, "skip", `class=${command.class}; --only=${ARGS.onlyFilter} excluded`));
				continue;
			}
			if (ARGS.skipFilter?.has(command.id)) {
				skipped.push(buildSkipped(command, "skip", `class=${command.class}; --skip filter excluded`));
				continue;
			}
			const runnable = command.class === "mandatory" || command.class === "affected-scope";
			if (!runnable) {
				skipped.push(buildSkipped(command, "skip", `class=${command.class} (not executed by runner)`));
				continue;
			}
			if (!command.host_support.includes(host)) {
				skipped.push(
					buildSkipped(command, "unavailable", `host=${host} not in host_support=${command.host_support.join(",")}`),
				);
				continue;
			}
			if (command.requires_gui && process.env.CI) {
				skipped.push(buildSkipped(command, "unavailable", "requires GUI; skipped on CI host"));
				continue;
			}

			attemptCount += 1;
			console.log(
				`[runner:${label}] (${attemptCount}) ${command.id} :: ${command.command ?? command.shell_command ?? command.argv?.join(" ")}`,
			);
			const result = await executeCommand(command, identityBefore, stagingDir, trackedInputs);
			executed.push(result);
			console.log(
				`[runner:${label}]   ${command.id} -> ${result.status} ` +
					`(${result.duration_ms}ms, exit=${result.exit_code ?? "n/a"}, class=${result.failure_classification ?? "n/a"})`,
			);
		}

		const merged = commands.map((command) => {
			const result = executed.find((row) => row.id === command.id) ?? skipped.find((row) => row.id === command.id);
			if (!result) {
				return {
					...command,
					result: "not-run",
					reason: "runner did not produce a row",
					failure_classification: null,
				};
			}
			return {
				...command,
				result: result.status,
				reason: result.notes,
				failure_classification: result.failure_classification,
			};
		});
		const resultDocument: PassResultDocument = {
			schema_version: 4,
			host,
			executed_at: new Date().toISOString(),
			executed_commands: executed,
			skipped_commands: skipped,
			commands: merged,
		};
		// CORRECTION13: the staged bundle is the authoritative executed-command
		// record. The tracked mirror at RESULTS_JSON is only refreshed after
		// the canonical swap succeeds so a failed pass cannot desync the
		// two halves of the "previous complete bundle" pair.
		const stagedResultPath = join(stagingDir, "verification-results.json");
		atomicWriteFile(stagedResultPath, JSON.stringify(resultDocument, null, "\t") + "\n");
		console.log(`Staged ${stagingDir}/verification-results.json executed=${executed.length} skipped=${skipped.length}`);

		// CORRECTION20: probe execution (the staged native-probes.json and
		// any artifact payloads) runs BEFORE the authoritative postflight
		// sample. The postflight still gates whether the pass publishes;
		// probe execution is observable in the runner's stdout but cannot
		// pollute the postflight sample because the probe collector is
		// read-only against the worktree (the staged copies live inside
		// the stagingDir, never the repository root).
		const {
			bundleRel: nativeProbesBundleRel,
			artifactPayloadRels,
			streamPayloadRels,
			inventory: probeInventory,
		} = await stageNativeProbesIntoBundle(stagingDir);

		const postflight = worktreeInputsClean();
		if (!postflight.clean) {
			throw new Error(`WORKTREE_INPUTS_DIRTY_AFTER: ${postflight.unexpected.join(", ")}`);
		}
		const identityAfter = captureExecutionIdentity();
		assertIdentityPinned(identityAfter, identityBefore, "REPOSITORY_DRIFT_END_OF_MATRIX");
		if (!verifyExecutionIdentityShape(identityAfter.head, identityAfter.tree)) {
			throw new Error("EXECUTION_IDENTITY_INVALID: postflight head/tree object relationship failed");
		}

		writeDetachedBundle({
			label,
			stagingDir,
			identity: identityBefore,
			preflight,
			postflight,
			resultDocument,
			nativeProbesBundleRel,
			artifactPayloadRels,
			streamPayloadRels,
		});
		replaceCanonicalBundle(stagingDir);
		// CORRECTION13 + CORRECTION20: refresh the tracked mirror only
		// after the canonical swap succeeded. The bundle is now
		// self-contained; the tracked file is informational and must not
		// be the authority. A failed pass cannot poison the tracked
		// mirror because this write happens after `replaceCanonicalBundle`
		// returns successfully.
		atomicWriteFile(
			join(ROOT, RESULTS_JSON),
			JSON.stringify(resultDocument, null, "\t") + "\n",
		);
		refreshTrackedNativeProbesMirror(probeInventory);
		console.log(`Published ${DETACHED_DIR} from one validated staging bundle`);
	} finally {
		// If publication succeeded this path no longer exists. Otherwise a
		// failed pass cannot disturb the previous complete canonical bundle.
		rmSync(stagingDir, {recursive: true, force: true});
	}
}

/**
 * Stage the native-probe inventory into the detached bundle and refresh the
 * tracked mirror. CORRECTION16: the staged copy is the authoritative source;
 * the tracked mirror at `factory/inventories/native-probes.json` is
 * informational only.
 *
 * Returns the bundle-relative payload path (`native-probes.json`) so the
 * manifest pass can hash-list it like any other evidence payload.
 *
 * The optional `probeInventoryPath` argument (driven by `--probe-inventory-path`)
 * is a test-fixture escape hatch: when set, the runner loads the inventory
 * from that file instead of executing probes. The fixture path is intended
 * for use by `run-verification.test.ts` only; production runs always go
 * through `collectNativeProbesInventory()`.
 */
async function stageNativeProbesIntoBundle(
	stagingDir: string,
	probeInventoryPath: string | null = ARGS.probeInventoryPath,
): Promise<{
	bundleRel: string;
	bundleAbs: string;
	artifactPayloadRels: string[];
	streamPayloadRels: string[];
	inventory: NativeProbesInventory;
}> {
	let inventory: NativeProbesInventory;
	if (probeInventoryPath !== null) {
		const text = readFileSync(probeInventoryPath, "utf8");
		inventory = JSON.parse(text) as NativeProbesInventory;
	} else {
		inventory = await collectNativeProbesInventory({ root: ROOT, timeoutMs: 30_000 });
	}
	const bundleRel = NATIVE_PROBES_BUNDLE_PATH;
	const bundleAbs = join(stagingDir, ...bundleRel.split("/"));
	writeInventory(inventory, bundleAbs);
	const artifactPayloadRels: string[] = [];
	for (const definition of NATIVE_PROBE_DEFINITIONS) {
		const probe = inventory.probes[definition.id];
		if (probe?.artifact_exists !== true) continue;
		const source = resolve(ROOT, ...definition.artifact_path.split("/"));
		if (!existsSync(source) || !lstatSync(source).isFile() || lstatSync(source).isSymbolicLink()) {
			throw new Error(`NATIVE_PROBE_ARTIFACT_MISSING: ${definition.id}: ${definition.artifact_path}`);
		}
		const stagedArtifact = join(stagingDir, ...definition.artifact_path.split("/"));
		atomicWriteFile(stagedArtifact, readFileSync(source));
		artifactPayloadRels.push(definition.artifact_path);
	}
	// CORRECTION21 (µC-2, completed) external-stream writer: for every
	// canonical probe, write the per-probe stdout, stderr, and
	// metadata.json payload into the bundle. The path is derived from
	// the probe id only; caller-selected alternative paths are
	// rejected. The hash recorded in `expected_evidence_payload_paths`
	// and `hashes.sha256` is computed from the exact bytes written, so
	// a self-attesting fixture cannot lie about the contents. Empty
	// stdout/stderr still produces present zero-byte files. All five
	// canonical probes are required; a missing record fails closed.
	// The probe record is enriched with the canonical stream-layout
	// fields and the recomputed stdout/stderr hashes before both the
	// aggregate `native-probes.json` and the per-probe `metadata.json`
	// are written, so the two are guaranteed to agree.
	const streamPayloadRels: string[] = [];
	const canonicalProbes = {} as Record<typeof NATIVE_PROBE_IDS[number], unknown>;
	for (const definition of NATIVE_PROBE_DEFINITIONS) {
		const probe = inventory.probes[definition.id];
		if (!probe) {
			throw new Error(
				`NATIVE_PROBE_RECORD_MISSING:${definition.id}: the canonical stream writer requires all five probe records; the inventory did not include one for ${definition.id}.`,
			);
		}
		// CORRECTION21 (µC-2 P0) missing stream text is rejected. An
		// empty string is a valid captured empty stream; a missing or
		// non-string field is rejected so a partial fixture cannot
		// silently pass as a valid empty stream.
		if (typeof probe.stdout_text !== "string") {
			throw new Error(
				`NATIVE_PROBE_STDOUT_MISSING:${definition.id}: the canonical stream writer requires a string stdout_text on the probe record; the inventory did not include one.`,
			);
		}
		if (typeof probe.stderr_text !== "string") {
			throw new Error(
				`NATIVE_PROBE_STDERR_MISSING:${definition.id}: the canonical stream writer requires a string stderr_text on the probe record; the inventory did not include one.`,
			);
		}
		const paths = canonicalStreamPaths(definition.id);
		const stdoutAbs = join(stagingDir, ...paths.stdout_path.split("/"));
		const stderrAbs = join(stagingDir, ...paths.stderr_path.split("/"));
		const metadataAbs = join(stagingDir, ...paths.metadata_path.split("/"));
		mkdirSync(dirname(stdoutAbs), { recursive: true });
		const stdoutBytes = Buffer.from(probe.stdout_text, "utf8");
		const stderrBytes = Buffer.from(probe.stderr_text, "utf8");
		atomicWriteFile(stdoutAbs, stdoutBytes);
		atomicWriteFile(stderrAbs, stderrBytes);
		const stdoutSha = sha256(stdoutBytes);
		const stderrSha = sha256(stderrBytes);
		// The canonical record: every field the loader will read for the
		// new schema, derived from the actual bytes staged on disk.
		// Note: hash consistency between staged bytes and the declared
		// SHA is guaranteed; production execution provenance (the
		// separate probe_source stamp) is what establishes whether the
		// bytes came from real probes. Hash consistency alone is not
		// authenticity.
		canonicalProbes[definition.id] = {
			...probe,
			stream_layout_version: 1,
			stdout_path: paths.stdout_path,
			stderr_path: paths.stderr_path,
			metadata_path: paths.metadata_path,
			stdout_sha256: stdoutSha,
			stderr_sha256: stderrSha,
		};
		atomicWriteFile(metadataAbs, JSON.stringify(canonicalProbes[definition.id], null, "\t") + "\n");
		streamPayloadRels.push(paths.stdout_path, paths.stderr_path, paths.metadata_path);
	}
	// Re-serialize the aggregate inventory with the canonical records
	// so the loader and the per-probe metadata.json agree.
	inventory.probes = canonicalProbes as typeof inventory.probes;
	writeInventory(inventory, bundleAbs);
	// CORRECTION20: the tracked mirror is NOT refreshed here. The tracked
	// file at `factory/inventories/native-probes.json` is informational
	// only; the authoritative copy is the staged bundle. Refreshing the
	// mirror inside this function would mean a partial / failed staging
	// pass leaves the mirror out of sync with the canonical bundle. The
	// caller (`runPass`) refreshes the mirror after `replaceCanonicalBundle`
	// succeeds, so a failed pass cannot poison the tracked file.
	return { bundleRel, bundleAbs, artifactPayloadRels, streamPayloadRels, inventory };
}

/**
 * Refresh the tracked native-probes mirror from a staged inventory that has
 * already been promoted into the canonical bundle. The tracked file is
 * informational; the canonical bundle remains the source of truth. Failures
 * here are logged but do not undo the canonical publish.
 */
function refreshTrackedNativeProbesMirror(inventory: NativeProbesInventory): void {
	const trackedMirror = join(ROOT, NATIVE_PROBES_INVENTORY_PATH);
	try {
		writeInventory(inventory, trackedMirror);
	} catch (error) {
		console.warn(
			`[runner] could not refresh tracked native-probes mirror: ${
				error instanceof Error ? error.message : String(error)
			}`,
		);
	}
}

function writeDetachedBundle(args: {
	label: string;
	stagingDir: string;
	identity: ExecutionIdentity;
	preflight: CleanlinessSample;
	postflight: CleanlinessSample;
	resultDocument: PassResultDocument;
	nativeProbesBundleRel: string;
	artifactPayloadRels: string[];
	streamPayloadRels: string[];
}): void {
	const {
		label,
		stagingDir,
		identity,
		preflight,
		postflight,
		resultDocument,
		nativeProbesBundleRel,
		artifactPayloadRels,
		streamPayloadRels,
	} = args;
	const executed = resultDocument.executed_commands;
	for (const row of executed) {
		for (const rel of [row.stdout_path, row.stderr_path, row.metadata_path]) {
			const resolved = resolveEvidencePayloadPath(stagingDir, ROOT, rel);
			if (!resolved.ok) throw new Error(`INVALID_EVIDENCE_PATH: ${row.id}: ${rel}: ${resolved.reason}`);
			if (!existsSync(resolved.abs) || !lstatSync(resolved.abs).isFile()) {
				throw new Error(`EVIDENCE_PAYLOAD_MISSING: ${row.id}: ${rel}`);
			}
		}
	}

	// CORRECTION13: verification-results.json is a first-class payload
	// inside the bundle; the renderer also reads it from staging.
	// CORRECTION16: native-probes.json is staged into the bundle before
	// the manifest is written so its SHA-256 is hash-listed in
	// `hashes.sha256` and the renderer can verify the inventory is
	// cryptographically bound to the bundle.
	const expectedEvidencePayloadPaths = executed.flatMap((row) => [
		row.stdout_path,
		row.stderr_path,
		row.metadata_path,
	]);
	expectedEvidencePayloadPaths.unshift(
		"evidence.json",
		"verification-results.json",
		nativeProbesBundleRel,
		...artifactPayloadRels,
		...streamPayloadRels,
	);

	const executionIdentityValid = verifyExecutionIdentityShape(identity.head, identity.tree);
	const evidence = {
		schema_version: 5,
		act_id: ACT_ID,
		pass_label: label,
		subject_tree_oid: identity.subject,
		subject_tree_oid_before: identity.subject,
		subject_tree_oid_after: identity.subject,
		execution_head_oid: identity.head,
		execution_tree_oid: identity.tree,
		execution_identity_valid: executionIdentityValid,
		worktree_inputs_clean_before: preflight.clean,
		worktree_inputs_clean_after: postflight.clean,
		worktree_inputs_clean_before_unexpected: preflight.unexpected,
		worktree_inputs_clean_after_unexpected: postflight.unexpected,
		worktree_clean_before: preflight.clean,
		worktree_clean_after: postflight.clean,
		// CORRECTION21: provenance stamp. The runner stamps
		// "executed"/false for production runs; the `--probe-inventory-path`
		// escape hatch (gated by `FACTORY_TEST_FIXTURE_MODE=1`) forces the
		// stamp to "fixture"/true so the closure refuses to satisfy
		// `isEvidenceOk` for fixtures. The runner cannot accidentally
		// satisfy the trust boundary by omitting the fields because the
		// schema enforces them on every write.
		probe_source: ARGS.probeInventoryPath === null ? "executed" : "fixture",
		fixture_derived: ARGS.probeInventoryPath !== null,
		expected_evidence_payload_paths: expectedEvidencePayloadPaths,
		tree_oid: identity.tree,
		head_oid: identity.head,
		generated_at: new Date().toISOString(),
		host_arch: resultDocument.host,
		subject_tree_excludes: SUBJECT_TREE_EXCLUDES.map((entry) => ({...entry})),
		commands: executed,
		hashes: {} as Record<string, string>,
	};

	for (const row of executed) {
		const stdout = readFileSync(join(stagingDir, ...row.stdout_path.split("/")));
		const stderr = readFileSync(join(stagingDir, ...row.stderr_path.split("/")));
		evidence.hashes[`${row.id}.stdout`] = sha256(stdout);
		evidence.hashes[`${row.id}.stderr`] = sha256(stderr);
		evidence.hashes[`${row.id}.stdout_stream`] = row.stdout_sha256;
		evidence.hashes[`${row.id}.stderr_stream`] = row.stderr_sha256;
	}

	atomicWriteFile(join(stagingDir, "evidence.json"), JSON.stringify(evidence, null, "\t") + "\n");
	const manifestLines = expectedEvidencePayloadPaths.map((rel) => {
		const resolved = resolveEvidencePayloadPath(stagingDir, ROOT, rel);
		if (!resolved.ok) throw new Error(`INVALID_EVIDENCE_PATH: ${rel}: ${resolved.reason}`);
		if (!existsSync(resolved.abs) || !lstatSync(resolved.abs).isFile()) {
			throw new Error(`EVIDENCE_PAYLOAD_MISSING: ${rel}`);
		}
		return `${sha256(readFileSync(resolved.abs))}  ${rel}`;
	});
	atomicWriteFile(join(stagingDir, "hashes.sha256"), `${manifestLines.join("\n")}\n`);

	// CORRECTION16: the native-probe inventory is verified from the bundle,
	// not from the tracked mirror. The verifier cross-checks the staged
	// inventory's hash against `hashes.sha256`, its execution identity
	// against the bundle identity, and every probe's recorded
	// `observed_architecture` / `host_class` / argv shape. Fail-closed:
	// any diagnostic makes `complete` false and the runner throws.
	const nativeProbes = loadNativeProbesFromEvidence({
		evDirAbs: stagingDir,
		manifestText: readFileSync(join(stagingDir, "hashes.sha256"), "utf8"),
		executionHeadOid: identity.head,
		executionTreeOid: identity.tree,
		filteredSubjectTreeOid: identity.subject,
	});
	if (!nativeProbes.complete) {
		const first = nativeProbes.diagnostics[0];
		throw new Error(
			`NATIVE_PROBES_INCOMPLETE: ${nativeProbes.diagnostics.length} diagnostic(s); ` +
				`first: ${first ? `${first.probeId}/${first.kind}: ${first.message}` : "(no diagnostic)"}`,
		);
	}

	const localView = checkEvidence({
		ev: loadEvidenceFile(join(stagingDir, "evidence.json")),
		hashesText: readFileSync(join(stagingDir, "hashes.sha256"), "utf8"),
		evDirAbs: stagingDir,
		executedCmds: executed,
		bundledResultPath: "verification-results.json",
		rootAbs: ROOT,
		headOidNow: identity.head,
		treeOidNow: identity.tree,
		filteredSubjectTreeOidNow: identity.subject,
		executionIdentityDerivation: deriveExecutionIdentityForLocalCheck(identity.head, identity.tree),
	});
	localView.nativeProbesComplete = nativeProbes.complete;
	localView.nativeProbesDiagnostics = nativeProbes.diagnostics;
	// CORRECTION21: the runner's self-check accepts both the
	// production stamp (`probe_source="executed"` + `fixture_derived=false`)
	// and the fixture stamp (`probe_source="fixture"` + `fixture_derived=true`).
	// `isEvidenceOk` rejects fixtures on purpose so the closure cannot
	// satisfy on a fixture; the runner's structural self-check is a
	// different concern (the bundle is internally consistent and the
	// probe dimension is complete). Mask the provenance fields here so
	// the structural check passes regardless of stamp; the closure
	// still rejects the fixture at render time.
	const fixtureInventoryInUse = ARGS.probeInventoryPath !== null;
	const selfCheckView: typeof localView = fixtureInventoryInUse
		? {...localView, probeSource: "executed", fixtureDerived: false}
		: localView;
	if (!isEvidenceOk(selfCheckView)) {
		throw new Error(
			`EVIDENCE_SELF_CHECK_FAILED: ${JSON.stringify({
				executionIdentityValid: localView.executionIdentityValid,
				perCommandDriftChecked: localView.perCommandDriftChecked,
				manifestContractHonored: localView.manifestContractHonored,
				hashManifestValid: localView.hashManifestValid,
				commandSetExact: localView.commandSetExact,
				bundledResultCommandSetExact: localView.bundledResultCommandSetExact,
				missingFiles: localView.missingFiles,
				unexpectedFiles: localView.unexpectedFiles,
				commandRecordMismatches: localView.commandRecordMismatches,
				malformedEvidenceCommandRows: localView.malformedEvidenceCommandRows,
				malformedExecutedCommandRows: localView.malformedExecutedCommandRows,
				rowRelationalInvariantViolations: localView.rowRelationalInvariantViolations,
				bundledResultExtraCommands: localView.bundledResultExtraCommands,
				bundledResultMissingCommands: localView.bundledResultMissingCommands,
			})}`,
		);
	}
	console.log(
		`Prepared detached evidence bundle once (${manifestLines.length} payloads, native probes complete)`,
	);
}

async function main(): Promise<void> {
	const verificationPath = join(ROOT, "factory/inventories/verification.json");
	if (!existsSync(verificationPath)) {
		throw new Error(`missing ${verificationPath}; run collect-verification first`);
	}
	verifyRunnerSourceBound();
	const document = JSON.parse(readFileSync(verificationPath, "utf8"));
	validateCommands(document.commands);
	const commands = document.commands;

	if (ARGS.finalize) {
		await runPass(commands, "finalize");
		return;
	}
	await runPass(commands, "execute");
}

if (import.meta.main) {
	main().catch((error) => {
		console.error(error);
		process.exitCode = 1;
	});
}
