#!/usr/bin/env bun
/**
 * ACT-CLINEMM-FORK-BASELINE01-CORRECTION10 — Filtered subject-tree helper.
 *
 * Computes a deterministic OID for HEAD's tree minus tracked outputs
 * generated by the verification workflow. The result is what evidence
 * bundles bind against under the CORRECTION10 subject-tree contract.
 *
 * CORRECTION10 fixes three provenance defects left by CORRECTION09:
 *
 *   1. Every `git update-index --force-remove` and `git ls-files` call
 *      now checks its exit status and returns `null` on failure. A
 *      non-zero exit used to be silently ignored, so the helper could
 *      return a valid OID while one or more supposedly-excluded paths
 *      were still present in the temporary index.
 *
 *   2. The exclusion list is now **structural**. `SUBJECT_TREE_EXCLUDES`
 *      is the single source of truth; each entry declares whether it
 *      matches an exact file or a directory prefix. The implementation
 *      no longer hard-codes `docs/factory/baseline-report.md` or
 *      `.factory` separately from the exported list.
 *
 *   3. The output tree is **verified** to contain none of the excluded
 *      paths before the OID is returned. This catches the case where a
 *      removal succeeded in the temp index but a later step reintroduced
 *      the path (defense in depth).
 *
 * The plumbing model is unchanged from CORRECTION09:
 *
 *   1. `git read-tree HEAD` populates a fresh index from HEAD's tree
 *      (preserves Git's hierarchy, modes, symlinks, submodule entries).
 *   2. `git update-index --force-remove <path>` (or per-path under a
 *      prefix) drops excluded entries from the temp index. `--force-remove`
 *      is required because a tracked-but-uncommitted file may not exist
 *      in the worktree.
 *   3. `git write-tree` emits a proper recursive tree OID. That OID is
 *      stable across regenerations of any excluded output.
 *
 * Subject vs. execution identity (CORRECTION10):
 *
 *   `computeFilteredSubjectTreeOid` returns the *filtered* subject tree.
 *   This is what `evidence.subject_tree_oid` and the renderer's
 *   `treeMatches` check compare. The runner also records the actual
 *   checked-out commit as `evidence.execution_head_oid` and its full
 *   `HEAD^{tree}` as `evidence.execution_tree_oid`. Those are the
 *   unfiltered values that command rows bind to.
 *
 * The temporary index lives in `os.tmpdir()` and is removed in `finally`.
 */

import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/**
 * Structural classification of an excluded path.
 *
 *   `file`   — exact path match. Removed with a single
 *              `git update-index --force-remove -- <path>`.
 *   `prefix` — directory prefix. All files under the prefix are
 *              enumerated with `git ls-files -z -- <prefix>` and each is
 *              removed individually.
 */
export type ExcludedPathKind = "file" | "prefix";

export interface ExcludedPath {
	kind: ExcludedPathKind;
	path: string;
}

/**
 * Subject-tree exclusion list. This is the **single source of truth**
 * for both the helper and the report renderer; changing it changes the
 * computed filtered OID.
 *
 * Excluded outputs are tracked artefacts generated or refreshed by the
 * verification workflow. The subject must contain everything that
 * influenced execution (schemas, command definitions, implementation)
 * but nothing generated by that execution (the closure report, the
 * detached evidence, and the regenerated inventory / baseline outputs).
 *
 * `SUBJECT_INPUTS` is the complement of this list within the tracked
 * tree; it is not enumerated explicitly.
 */
export const SUBJECT_TREE_EXCLUDES: ReadonlyArray<ExcludedPath> = [
	// The closure report itself — a tracked file generated by the renderer.
	{ kind: "file", path: "docs/factory/baseline-report.md" },
	// The detached evidence directory — written by the runner and excluded
	// from the worktree subject by construction.
	{ kind: "prefix", path: ".factory" },
	// Tracked execution outputs (regenerated by collectors and the runner):
	{ kind: "file", path: "factory/inventories/verification-results.json" },
	{ kind: "file", path: "factory/inventories/environment.json" },
	{ kind: "file", path: "factory/inventories/repository.json" },
	{ kind: "file", path: "factory/inventories/workspaces.json" },
	{ kind: "file", path: "factory/inventories/native-probes.json" },
	{ kind: "file", path: "factory/inventories/network-listener-candidates.csv" },
	{ kind: "file", path: "factory/inventories/privileged-sink-candidates.csv" },
	{ kind: "file", path: "factory/baselines/file-size-summary.json" },
	{ kind: "file", path: "factory/baselines/file-size.csv" },
	{ kind: "file", path: "factory/baselines/exact-duplicates.json" },
];

const OID_PATTERN = /^[0-9a-f]{40}$/;

/**
 * Compute the OID of HEAD's tree minus `SUBJECT_TREE_EXCLUDES`. Returns
 * `null` if any git step fails (no HEAD, git missing, missing tools,
 * exclusion-removal failed, output verification failed, etc.). The
 * caller is responsible for treating `null` as fail-closed.
 */
export function computeFilteredSubjectTreeOid(root: string): string | null {
	const tmp = mkdtempSync(join(tmpdir(), "factory-subject-tree-"));
	const tmpIndex = join(tmp, "index");
	try {
		// 1. Populate a fresh index from HEAD.
		const rt = runGit(root, ["read-tree", "HEAD"], tmpIndex);
		if (rt.status !== 0) return null;

		// 2. Drop every excluded entry, driven by SUBJECT_TREE_EXCLUDES.
		//    Every `git update-index` and `git ls-files` call has its exit
		//    status checked; a non-zero status is a real computation
		//    failure and must fail closed.
		for (const ex of SUBJECT_TREE_EXCLUDES) {
			if (ex.kind === "file") {
				const r = runGit(
					root,
					["update-index", "--force-remove", "--", ex.path],
					tmpIndex,
				);
				if (r.status !== 0) return null;
			} else {
				// prefix: enumerate, then remove each. ls-files failure
				// is treated as a real failure — the caller cannot claim
				// the prefix is excluded without enumerating it.
				const ls = runGitBuffer(
					root,
					["ls-files", "-z", "--", ex.path],
					tmpIndex,
				);
				if (ls.status !== 0) return null;
				const files = (ls.stdout as Buffer)
					.toString("utf8")
					.split("\0")
					.filter(Boolean);
				for (const f of files) {
					const r = runGit(
						root,
						["update-index", "--force-remove", "--", f],
						tmpIndex,
					);
					if (r.status !== 0) return null;
				}
			}
		}

		// 3. Emit the filtered tree OID.
		const wt = runGit(root, ["write-tree"], tmpIndex);
		if (wt.status !== 0) return null;
		const out = (wt.stdout ?? "").trim();
		if (!OID_PATTERN.test(out)) return null;

		// 4. Defense in depth: verify the resulting tree contains none of
		//    the excluded paths. If any survived the removal pass, return
		//    `null` rather than a misleading OID.
		if (!verifyExcludesAbsent(root, out)) return null;

		return out;
	} finally {
		try {
			rmSync(tmp, { recursive: true, force: true });
		} catch {
			// best-effort cleanup
		}
	}
}

/**
 * Confirm that `git ls-tree -r <oid>` contains no excluded paths.
 * Returns `false` (computation failure) if any excluded file or any
 * path under an excluded prefix still appears.
 */
function verifyExcludesAbsent(root: string, oid: string): boolean {
	const r = runGitBuffer(root, ["ls-tree", "-r", oid], "");
	if (r.status !== 0) return false;
	const text = (r.stdout as Buffer).toString("utf8");
	const entries = parseLsTree(text);
	const present = new Set(entries);
	for (const ex of SUBJECT_TREE_EXCLUDES) {
		if (ex.kind === "file") {
			if (present.has(ex.path)) return false;
		} else {
			const prefix = ex.path.endsWith("/") ? ex.path : ex.path + "/";
			for (const e of present) {
				if (e === ex.path || e.startsWith(prefix)) return false;
			}
		}
	}
	return true;
}

/**
 * Parse `git ls-tree -r` output (one entry per line: `<mode> <type> <oid>\t<path>`).
 * Returns the set of paths.
 */
function parseLsTree(text: string): string[] {
	const out: string[] = [];
	for (const line of text.split("\n")) {
		if (line.length === 0) continue;
		const tab = line.indexOf("\t");
		if (tab < 0) continue;
		out.push(line.slice(tab + 1));
	}
	return out;
}

function runGit(
	root: string,
	args: string[],
	gitIndexFile: string,
): { status: number | null; stdout: string } {
	const r = spawnSync("git", args, {
		encoding: "utf8",
		cwd: root,
		env: { ...process.env, GIT_INDEX_FILE: gitIndexFile },
		stdio: ["ignore", "pipe", "pipe"],
	});
	return { status: r.status, stdout: (r.stdout ?? "").toString() };
}

function runGitBuffer(
	root: string,
	args: string[],
	gitIndexFile: string,
): { status: number | null; stdout: Buffer } {
	const r = spawnSync("git", args, {
		cwd: root,
		env: { ...process.env, GIT_INDEX_FILE: gitIndexFile },
		stdio: ["ignore", "pipe", "pipe"],
	});
	return { status: r.status, stdout: r.stdout ?? Buffer.alloc(0) };
}
