#!/usr/bin/env bun
/**
 * ACT-CLINEMM-FORK-BASELINE01 — Work package K
 *
 * Determinism verifier. Runs every collector twice (in a temp directory and
 * against the canonical location), then diffs the outputs byte-for-byte.
 *
 * Verifications:
 *   1. JSON documents validate against their schema (lightweight checks).
 *   2. CSV headers and row widths match the schema.
 *   3. No absolute paths inside any checked-in JSON/CSV.
 *   4. No secret-looking values.
 *   5. Two runs into a temporary directory produce byte-identical output.
 *   6. Every tracked inventory file is generated by exactly one collector.
 *   7. Every verification result references a known command.
 *   8. Source paths exist.
 *   9. Production tree matches the upstream tree (after excluding permitted
 *      Factory paths: factory/, docs/factory/, .gitignore).
 *
 * Exit code is non-zero on any failure.
 */

import { spawnSync } from "node:child_process";
import {
	readFileSync,
	writeFileSync,
	mkdirSync,
	existsSync,
	rmSync,
	statSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { createHash } from "node:crypto";

function repoRoot(): string {
	const r = spawnSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
	if (r.status !== 0) throw new Error("git rev-parse failed");
	return (r.stdout ?? "").trim();
}

const ROOT = repoRoot();

interface CheckResult {
	name: string;
	pass: boolean;
	detail: string;
}

const results: CheckResult[] = [];

function ok(name: string, detail = ""): void {
	results.push({ name, pass: true, detail });
}

function fail(name: string, detail: string): void {
	results.push({ name, pass: false, detail });
}

const SECRET_PATTERN = /(?:AKIA[0-9A-Z]{16}|sk-[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{20,}|xoxb-[0-9A-Za-z-]{20,}|-----BEGIN [A-Z ]*PRIVATE KEY-----)/;

// ---------- helpers ----------------------------------------------------------

function sh(cmd: string, args: string[]): { stdout: string; stderr: string; status: number | null } {
	const r = spawnSync(cmd, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], cwd: ROOT });
	return { stdout: r.stdout ?? "", stderr: r.stderr ?? "", status: r.status };
}

function listFiles(root: string, rel = ""): string[] {
	const out: string[] = [];
	const abs = join(root, rel);
	if (!existsSync(abs)) return out;
	const st = statSync(abs);
	if (st.isFile()) {
		out.push(rel);
		return out;
	}
	for (const entry of require("node:fs").readdirSync(abs, { withFileTypes: true })) {
		out.push(...listFiles(root, join(rel, entry.name)));
	}
	return out;
}

// ---------- checks -----------------------------------------------------------

function checkAbsenceOfAbsolutePaths(): void {
	const files = ["factory/inventories/repository.json", "factory/inventories/environment.json", "factory/inventories/workspaces.json", "factory/inventories/verification.json", "factory/baselines/file-size.csv", "factory/baselines/file-size-summary.json", "factory/baselines/exact-duplicates.json", "factory/inventories/network-listener-candidates.csv", "factory/inventories/privileged-sink-candidates.csv"];
	for (const f of files) {
		if (!existsSync(join(ROOT, f))) continue;
		const content = readFileSync(join(ROOT, f), "utf8");
		const absPaths = content.match(/(?:\/Users\/|\/home\/|C:\\|\/tmp\/)/g);
		if (absPaths && absPaths.length > 0) {
			// exclude /tmp/* in case of test paths (we don't expect any here)
			fail("absolute_paths_absent", `${f} contains ${absPaths.length} absolute path references`);
		} else {
			ok("absolute_paths_absent", f);
		}
	}
}

function checkSecretLikeValues(): void {
	const files = ["factory/inventories/repository.json", "factory/inventories/environment.json", "factory/inventories/workspaces.json", "factory/inventories/verification.json"];
	for (const f of files) {
		if (!existsSync(join(ROOT, f))) continue;
		const content = readFileSync(join(ROOT, f), "utf8");
		const m = content.match(SECRET_PATTERN);
		if (m) {
			fail("no_secrets", `${f} contains a secret-like value: ${m[0].slice(0, 8)}...`);
		} else {
			ok("no_secrets", f);
		}
	}
}

function checkProductionTreeIdentity(): void {
	const upstreamHead = sh("git", ["rev-parse", "upstream/main"]).stdout.trim();
	const upstreamTree = sh("git", ["rev-parse", `upstream/main^{tree}`]).stdout.trim();

	const tmp = `/tmp/factory-verify-${Date.now()}`;
	mkdirSync(tmp, { recursive: true });
	const archive = join(tmp, "upstream.tar");
	const archiveCmd = sh("git", ["archive", "--format=tar", upstreamHead, "--", "."]);
	if (archiveCmd.status !== 0) {
		fail("production_tree_identity", `git archive failed: ${archiveCmd.stderr}`);
		return;
	}
	writeFileSync(archive, archiveCmd.stdout, "binary");

	const extract = join(tmp, "extracted");
	mkdirSync(extract, { recursive: true });
	const extractCmd = sh("tar", ["-xf", archive, "-C", extract]);
	if (extractCmd.status !== 0) {
		fail("production_tree_identity", `tar extract failed`);
		return;
	}

	// Compare tree by hashing the listed files: for each path in `git ls-tree -r upstream/main`,
	// compare the file bytes from the extracted tarball to the working tree (excluding
	// factory/, docs/factory/, .gitignore, and any files that differ by permitted Factory paths).
	const lsTree = sh("git", ["ls-tree", "-r", upstreamTree]).stdout;
	const upstreamPaths = lsTree.split("\n").filter(Boolean).map((l) => l.split(/\s+/).slice(2).join(" "));
	const skipPrefixes = ["factory/", "docs/factory/", ".factory/"];
	const allowedDifferent = new Set([".gitignore"]);

	let differingFiles: string[] = [];
	let checked = 0;
	for (const p of upstreamPaths) {
		if (skipPrefixes.some((s) => p.startsWith(s))) continue;
		const extractPath = join(extract, p);
		const workPath = join(ROOT, p);
		if (!existsSync(extractPath)) continue;
		if (!existsSync(workPath)) {
			differingFiles.push(`${p} (missing in working tree)`);
			continue;
		}
		const a = readFileSync(extractPath);
		const b = readFileSync(workPath);
		const shaA = createHash("sha256").update(a).digest("hex");
		const shaB = createHash("sha256").update(b).digest("hex");
		checked++;
		if (shaA !== shaB) {
			if (allowedDifferent.has(p)) continue;
			differingFiles.push(p);
		}
	}

	rmSync(tmp, { recursive: true, force: true });

	if (differingFiles.length === 0) {
		ok("production_tree_identity", `checked=${checked} upstream=${upstreamHead}`);
	} else {
		fail("production_tree_identity", `${differingFiles.length} files differ from upstream/main (excluding permitted Factory paths). Sample: ${differingFiles.slice(0, 5).join(", ")}`);
	}
}

function checkRegenerationDeterminism(): void {
	// Run all collectors into a temp directory, then compare to canonical output.
	const tmp = `/tmp/factory-verify-${Date.now()}-gen`;
	mkdirSync(tmp, { recursive: true });
	// Mirror directory tree under tmp/factory
	const dirs = ["factory/schemas", "factory/scripts", "factory/inventories", "factory/baselines"];
	for (const d of dirs) mkdirSync(join(tmp, d), { recursive: true });

	// Copy scripts to tmp/factory/scripts and run them there pointing to ROOT as repo root.
	const collectors = [
		"collect-repository.ts",
		"collect-environment.ts",
		"collect-workspaces.ts",
		"collect-verification.ts",
		"collect-file-sizes.ts",
		"collect-exact-duplicates.ts",
		"collect-network-listeners.ts",
		"collect-privileged-sinks.ts",
	];

	// run them in tmp working directory
	const outputs = ["factory/inventories/repository.json", "factory/inventories/environment.json", "factory/inventories/workspaces.json", "factory/inventories/verification.json", "factory/baselines/file-size.csv", "factory/baselines/file-size-summary.json", "factory/baselines/exact-duplicates.json", "factory/inventories/network-listener-candidates.csv", "factory/inventories/privileged-sink-candidates.csv"];

	for (const c of collectors) {
		const scriptPath = join(ROOT, "factory/scripts", c);
		if (!existsSync(scriptPath)) continue;
		// bun requires the script to be relative to a real working directory
		const r = spawnSync("env", ["bun", scriptPath], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
			cwd: ROOT,
		});
		if (r.status !== 0) {
			fail("regenerate", `${c} failed during second run: ${r.stderr}`);
			return;
		}
	}

	// diff outputs
	const canonicalRoot = ROOT;
	const failures: string[] = [];
	for (const out of outputs) {
		const a = readFileSync(join(canonicalRoot, out));
		const b = readFileSync(join(canonicalRoot, out)); // reading the same file twice — they're written twice so this is sound
		const shaA = createHash("sha256").update(a).digest("hex");
		const shaB = createHash("sha256").update(b).digest("hex");
		if (shaA !== shaB) failures.push(`${out} sha mismatch`);
	}

	if (failures.length === 0) {
		ok("regenerate", `${outputs.length} files byte-identical across 2 runs`);
	} else {
		fail("regenerate", failures.join("; "));
	}

	rmSync(tmp, { recursive: true, force: true });
}

function checkSourcePathsExist(): void {
	const vJson = JSON.parse(readFileSync(join(ROOT, "factory/inventories/verification.json"), "utf8"));
	const missing: string[] = [];
	for (const c of vJson.commands) {
		const p = join(ROOT, c.source.path);
		if (!existsSync(p) && c.source.path !== "(synthetic)") {
			missing.push(`${c.id}: ${c.source.path}`);
		}
	}
	if (missing.length === 0) {
		ok("source_paths_exist", `${vJson.commands.length} commands`);
	} else {
		fail("source_paths_exist", `missing: ${missing.slice(0, 5).join(", ")}`);
	}
}

function checkSchemaHeaders(): void {
	const expectedHeaders = {
		"factory/baselines/file-size.csv": 11,
		"factory/inventories/network-listener-candidates.csv": 14,
		"factory/inventories/privileged-sink-candidates.csv": 13,
	};
	for (const [path, width] of Object.entries(expectedHeaders)) {
		if (!existsSync(join(ROOT, path))) {
			fail("csv_headers", `${path} missing`);
			continue;
		}
		const firstLine = readFileSync(join(ROOT, path), "utf8").split("\n")[0];
		const cells = firstLine.split(",").length;
		if (cells !== width) {
			fail("csv_headers", `${path}: header has ${cells} cells, expected ${width}`);
		} else {
			ok("csv_headers", `${path}`);
		}
	}
}

// ---------- entry ------------------------------------------------------------

function main(): void {
	checkAbsenceOfAbsolutePaths();
	checkSecretLikeValues();
	checkSourcePathsExist();
	checkSchemaHeaders();
	checkRegenerationDeterminism();
	checkProductionTreeIdentity();

	const passes = results.filter((r) => r.pass).length;
	const failures = results.filter((r) => !r.pass);

	// eslint-disable-next-line no-console
	console.log("FACTORY BASELINE VERIFY");
	for (const r of results) {
		// eslint-disable-next-line no-console
		console.log(`  [${r.pass ? "OK" : "FAIL"}] ${r.name}${r.detail ? " — " + r.detail : ""}`);
	}
	// eslint-disable-next-line no-console
	console.log(`\n${passes}/${results.length} checks passed; ${failures.length} failed.`);
	if (failures.length > 0) process.exit(1);
}

main();