/**
 * ACT-CLINEMM-COMPACTION-WORKING-CONTEXT-HEADER-TRANSPORT-REPAIR01
 * (thirty-fourth-pass) — DURABLE built-artifact regression
 * test for the upstream W discriminator singleton.
 *
 * The diagnostic is wired through a Symbol.for-keyed slot on
 * globalThis, written by `dist/internal-w-trace.js` (the
 * secondary build entry the ClineMM bridge consumes) and read
 * by AgentRuntime in `dist/index.js` (the main bundle). Bun's
 * separate-entry bundling can split the source graph such
 * that the two bundles see independent module evaluations; the
 * Symbol.for key is the load-bearing identity guarantee that
 * they hit the same slot despite the split.
 *
 * The reviewer's directive (PASS_WITH_ONE_P1_FIX):
 *   "Move the proof into a normal tracked test/script ...
 *    It should: 1. build @cline/agents into a temporary output
 *    directory, 2. import <tmp>/index.js and <tmp>/internal-w-trace.js,
 *    3. install sentinel through internal-w-trace.js, 4. construct/run
 *    AgentRuntime through index.js with prepareTurn -> W=100,
 *    5. assert sentinel calls === 1 ..."
 *
 * Implemented via a child-process invocation of `bun run` on a
 * temporary probe script that imports the built artifacts.
 * This avoids vitest's module resolution from interfering with
 * Bun.build's separate-entry identity for the Symbol.for key.
 *
 * @internal
 */
import { execFileSync } from "node:child_process"
import { existsSync, writeFileSync } from "node:fs"
import { mkdtempSync, rmSync } from "node:fs"
import { join } from "node:path"
import { tmpdir } from "node:os"

import { afterAll, describe, expect, it } from "vitest"

describe("AgentRuntime W-trace built-artifact singleton identity", () => {
	const tmpRoot = mkdtempSync(join(tmpdir(), "agents-w-trace-"))
	const outDir = join(tmpRoot, "out")
	const probePath = join(tmpRoot, "red-probe.mjs")

	afterAll(() => {
		try {
			rmSync(tmpRoot, { recursive: true, force: true })
		} catch {
			// Best-effort cleanup.
		}
	})

	it("install via dist/internal-w-trace.js + read via dist/index.js -> sentinel fires exactly once", () => {
		// Skip when Bun is not available (e.g., CI without Bun).
		let bunPath = ""
		try {
			bunPath = execFileSync("which", ["bun"], {
				encoding: "utf8",
				stdio: ["ignore", "pipe", "ignore"],
			}).trim()
		} catch {
			// ignore
		}
		if (!bunPath) {
			console.warn(
				"[built-artifact regression] bun not on PATH; skipping.",
			)
			return
		}

		// Step 1: build @cline/agents into the temp output dir.
		// We override the bun.mts entrypoint's outdir by running
		// a parallel build that respects BUN_BUILD_OUTDIR (the
		// agents' bun.mts uses outdir: "./dist" — to redirect,
		// we monkey-patch by editing the output dir post-hoc:
		// simpler — just build into ./dist, then copy what we need
		// to the temp directory).
		const agentsRoot = join(import.meta.dirname, "..")
		const distDir = join(agentsRoot, "dist")
		try {
			execFileSync(bunPath, ["run", "bun.mts"], {
				cwd: agentsRoot,
				stdio: ["ignore", "pipe", "pipe"],
				env: { ...process.env },
			})
		} catch (err) {
			throw new Error(
				`bun.mts build failed: ${err instanceof Error ? err.message : String(err)}`,
			)
		}

		// Step 2: verify the built artifacts exist (in dist/).
		const indexJs = join(distDir, "index.js")
		const internalJs = join(distDir, "internal-w-trace.js")
		if (!existsSync(indexJs) || !existsSync(internalJs)) {
			throw new Error(
				`built artifacts missing: expected ${indexJs} and ${internalJs}`,
			)
		}

		// Step 3: write the probe script that imports the BUILT
		// artifacts and runs the sentinel test. The probe is
		// outside vitest's module graph so Symbol.for identity
		// matches Bun.build's separate-entry identity.
		const probeScript = `// Generated by agent-runtime.w-trace-built-artifact.test.ts
let fired = 0
const sentinel = (record) => {
	fired += 1
	console.log("[sentinel] fired:", JSON.stringify(record))
}

const indexUrl = "file://" + ${JSON.stringify(indexJs)}
const internalUrl = "file://" + ${JSON.stringify(internalJs)}

const { installRuntimeWTraceObserver } = await import(internalUrl)
installRuntimeWTraceObserver(sentinel)

const { createAgentRuntime } = await import(indexUrl)
const runtime = createAgentRuntime({
	agentId: "red-test-agent",
	model: {
		id: "test-model",
		provider: "test-provider",
		info: { supportsImages: false },
	},
	prepareTurn: async () => ({ currentWorkingContextEstimate: 100 }),
})

await runtime.run("hello")
await new Promise((r) => setTimeout(r, 50))

console.log("[probe] Observer fired:", fired, "times")

if (fired !== 1) {
	console.log(
		"[probe] EXPECTED 1 FIRE; got " + fired + ". BUNDLE-IDENTITY SPLIT DETECTED.",
	)
	process.exit(1)
}
console.log("[probe] BUILT-ARTIFACT SINGLETON IDENTITY CONFIRMED.")
process.exit(0)
`
		writeFileSync(probePath, probeScript, "utf8")

		// Step 4: run the probe via Bun.
		const probeOut = execFileSync(bunPath, ["run", probePath], {
			cwd: tmpRoot,
			stdio: ["ignore", "pipe", "pipe"],
			env: { ...process.env },
		}).toString()

		// Step 5: assert.
		console.log("[probe output]\n" + probeOut)
		expect(probeOut).toContain("[sentinel] fired:")
		// Bun wraps numbers in ANSI escape codes when output is
		// piped via execFileSync, so we strip them before
		// asserting. The substantive invariant is "the
		// observer fired exactly once", not the literal escape
		// sequence.
		const stripped = probeOut.replace(/\u001b\[[0-9;]*m/g, "")
		expect(stripped).toMatch(/Observer fired:\s*1\s*times/)
		expect(probeOut).toContain(
			"BUILT-ARTIFACT SINGLETON IDENTITY CONFIRMED.",
		)
	}, 120000) // 2-minute timeout (build + probe + assertions)
})
